In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
# Load the smaller files
stations = pd.read_csv('stations.csv')
city_day = pd.read_csv('city_day.csv')
city_hour = pd.read_csv('city_hour.csv')
station_day = pd.read_csv('station_day.csv')

# Load the large file (low_memory=False prevents warnings for big files)
station_hour = pd.read_csv('station_hour.csv', low_memory=False)

print("All files loaded successfully!")

All files loaded successfully!

In [3]:
stations.info()
stations.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StationId    230 non-null    object
 1   StationName  230 non-null    object
 2   City         230 non-null    object
 3   State        230 non-null    object
 4   Status       133 non-null    object
dtypes: object(5)
memory usage: 9.1+ KB

StationId       0
StationName     0
City            0
State           0
Status         97
dtype: int64

In [4]:
stations.head(20)

,StationId,StationName,City,State,Status
0,AP001,"Secretariat, Amaravati - APPCB",Amaravati,Andhra Pradesh,Active
1,AP002,"Anand Kala Kshetram, Rajamahendravaram - APPCB",Rajamahendravaram,Andhra Pradesh,NaN
2,AP003,"Tirumala, Tirupati - APPCB",Tirupati,Andhra Pradesh,NaN
3,AP004,"PWD Grounds, Vijayawada - APPCB",Vijayawada,Andhra Pradesh,NaN
4,AP005,"GVM Corporation, Visakhapatnam - APPCB",Visakhapatnam,Andhra Pradesh,Active
5,AS001,"Railway Colony, Guwahati - APCB",Guwahati,Assam,Active
6,BR001,"Collectorate, Gaya - BSPCB",Gaya,Bihar,NaN
7,BR002,"SFTI Kusdihra, Gaya - BSPCB",Gaya,Bihar,NaN
8,BR003,"Industrial Area, Hajipur - BSPCB",Hajipur,Bihar,NaN
9,BR004,"Muzaffarpur Collectorate, Muzaffarpur - BSPCB",Muzaffarpur,Bihar,NaN
10,BR005,"DRM Office Danapur, Patna - BSPCB",Patna,Bihar,Active
11,BR006,"Govt. High School Shikarpur, Patna - BSPCB",Patna,Bihar,Active
12,BR007,"IGSC Planetarium Complex, Patna - BSPCB",Patna,Bihar,Active
13,BR008,"Muradpur, Patna - BSPCB",Patna,Bihar,Active
14,BR009,"Rajbansi Nagar, Patna - BSPCB",Patna,Bihar,Active
15,BR010,"Samanpura, Patna - BSPCB",Patna,Bihar,Active
16,CH001,"Sector-25, Chandigarh - CPCC",Chandigarh,Chandigarh,Active
17,DL001,"Alipur, Delhi - DPCC",Delhi,Delhi,Active
18,DL002,"Anand Vihar, Delhi - DPCC",Delhi,Delhi,Active
19,DL003,"Ashok Vihar, Delhi - DPCC",Delhi,Delhi,Active

In [5]:
print(stations.duplicated().sum())
stations.describe()

0

       StationId                     StationName   City  State  Status
count        230                             230    230    230     133
unique       230                             230    127     21       2
top        AP001  Secretariat, Amaravati - APPCB  Delhi  Delhi  Active
freq           1                               1     38     38     131

In [6]:
stations['Status'].unique()
print(stations['Status'].value_counts())

Status
Active      131
Inactive      2
Name: count, dtype: int64

In [7]:
stations['Status'].isnull().sum()

np.int64(97)

In [8]:
stations["Status"].mode()[0]

'Active'

In [9]:
stations['Status'] = stations['Status'].fillna('Unknown')

In [10]:
stations['Status']

0       Active
1      Unknown
2      Unknown
3      Unknown
4       Active
        ...
225     Active
226     Active
227     Active
228     Active
229    Unknown
Name: Status, Length: 230, dtype: object

In [11]:
stations.tail(20)

,StationId,StationName,City,State,Status
210,UP021,"New Mandi, Muzaffarnagar - UPPCB",Muzzaffarnagar,Uttar Pradesh,Unknown
211,UP022,"Sector - 125, Noida - UPPCB",Noida,Uttar Pradesh,Unknown
212,UP023,"Sector - 62, Noida - IMD",Noida,Uttar Pradesh,Unknown
213,UP024,"Sector-1, Noida - UPPCB",Noida,Uttar Pradesh,Unknown
214,UP025,"Sector-116, Noida - UPPCB",Noida,Uttar Pradesh,Unknown
215,UP026,"Ardhali Bazar, Varanasi - UPPCB",Varanasi,Uttar Pradesh,Unknown
216,WB001,"Asansol Court Area, Asansol - WBPCB",Asansol,West Bengal,Unknown
217,WB002,"Sidhu Kanhu Indoor Stadium, Durgapur - WBPCB",Durgapur,West Bengal,Unknown
218,WB003,"Haldia, Haldia - WBPCB",Haldia,West Bengal,Unknown
219,WB004,"Belur Math, Howrah - WBPCB",Howrah,West Bengal,Unknown
220,WB005,"Ghusuri, Howrah - WBPCB",Howrah,West Bengal,Unknown
221,WB006,"Padmapukur, Howrah - WBPCB",Howrah,West Bengal,Unknown
222,WB007,"Ballygunge, Kolkata - WBPCB",Kolkata,West Bengal,Active
223,WB008,"Bidhannagar, Kolkata - WBPCB",Kolkata,West Bengal,Active
224,WB009,"Fort William, Kolkata - WBPCB",Kolkata,West Bengal,Active
225,WB010,"Jadavpur, Kolkata - WBPCB",Kolkata,West Bengal,Active
226,WB011,"Rabindra Bharati University, Kolkata - WBPCB",Kolkata,West Bengal,Active
227,WB012,"Rabindra Sarobar, Kolkata - WBPCB",Kolkata,West Bengal,Active
228,WB013,"Victoria, Kolkata - WBPCB",Kolkata,West Bengal,Active
229,WB014,"Ward-32 Bapupara, Siliguri - WBPCB",Siliguri,West Bengal,Unknown

In [12]:
stations.head(20)

,StationId,StationName,City,State,Status
0,AP001,"Secretariat, Amaravati - APPCB",Amaravati,Andhra Pradesh,Active
1,AP002,"Anand Kala Kshetram, Rajamahendravaram - APPCB",Rajamahendravaram,Andhra Pradesh,Unknown
2,AP003,"Tirumala, Tirupati - APPCB",Tirupati,Andhra Pradesh,Unknown
3,AP004,"PWD Grounds, Vijayawada - APPCB",Vijayawada,Andhra Pradesh,Unknown
4,AP005,"GVM Corporation, Visakhapatnam - APPCB",Visakhapatnam,Andhra Pradesh,Active
5,AS001,"Railway Colony, Guwahati - APCB",Guwahati,Assam,Active
6,BR001,"Collectorate, Gaya - BSPCB",Gaya,Bihar,Unknown
7,BR002,"SFTI Kusdihra, Gaya - BSPCB",Gaya,Bihar,Unknown
8,BR003,"Industrial Area, Hajipur - BSPCB",Hajipur,Bihar,Unknown
9,BR004,"Muzaffarpur Collectorate, Muzaffarpur - BSPCB",Muzaffarpur,Bihar,Unknown
10,BR005,"DRM Office Danapur, Patna - BSPCB",Patna,Bihar,Active
11,BR006,"Govt. High School Shikarpur, Patna - BSPCB",Patna,Bihar,Active
12,BR007,"IGSC Planetarium Complex, Patna - BSPCB",Patna,Bihar,Active
13,BR008,"Muradpur, Patna - BSPCB",Patna,Bihar,Active
14,BR009,"Rajbansi Nagar, Patna - BSPCB",Patna,Bihar,Active
15,BR010,"Samanpura, Patna - BSPCB",Patna,Bihar,Active
16,CH001,"Sector-25, Chandigarh - CPCC",Chandigarh,Chandigarh,Active
17,DL001,"Alipur, Delhi - DPCC",Delhi,Delhi,Active
18,DL002,"Anand Vihar, Delhi - DPCC",Delhi,Delhi,Active
19,DL003,"Ashok Vihar, Delhi - DPCC",Delhi,Delhi,Active

In [13]:
city_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [14]:
city_day.head(20)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
5,Ahmedabad,2015-01-06,NaN,NaN,45.41,38.48,81.50,NaN,45.41,45.76,46.51,5.42,10.83,1.93,NaN,NaN
6,Ahmedabad,2015-01-07,NaN,NaN,112.16,40.62,130.77,NaN,112.16,32.28,33.47,0.00,0.00,0.00,NaN,NaN
7,Ahmedabad,2015-01-08,NaN,NaN,80.87,36.74,96.75,NaN,80.87,38.54,31.89,0.00,0.00,0.00,NaN,NaN
8,Ahmedabad,2015-01-09,NaN,NaN,29.16,31.00,48.00,NaN,29.16,58.68,25.75,0.00,0.00,0.00,NaN,NaN
9,Ahmedabad,2015-01-10,NaN,NaN,NaN,7.04,0.00,NaN,NaN,8.29,4.55,0.00,0.00,0.00,NaN,NaN
10,Ahmedabad,2015-01-11,NaN,NaN,132.07,55.80,24.53,NaN,132.07,25.03,6.79,0.00,0.00,0.00,NaN,NaN
11,Ahmedabad,2015-01-12,NaN,NaN,52.04,40.67,90.24,NaN,52.04,51.84,45.89,2.41,0.03,7.88,NaN,NaN
12,Ahmedabad,2015-01-13,NaN,NaN,48.82,44.20,87.09,NaN,48.82,68.21,35.16,9.45,13.35,12.50,NaN,NaN
13,Ahmedabad,2015-01-14,NaN,NaN,19.20,27.86,33.05,NaN,19.20,52.65,20.96,2.16,2.26,5.19,NaN,NaN
14,Ahmedabad,2015-01-15,NaN,NaN,0.60,16.96,16.60,NaN,0.60,28.89,47.63,0.14,0.04,1.35,NaN,NaN
15,Ahmedabad,2015-01-16,NaN,NaN,1.63,21.72,22.86,NaN,1.63,38.27,46.03,0.35,0.05,2.01,NaN,NaN
16,Ahmedabad,2015-01-17,NaN,NaN,11.44,24.73,34.75,NaN,11.44,49.50,52.24,0.68,0.00,3.27,NaN,NaN
17,Ahmedabad,2015-01-18,NaN,NaN,6.10,25.77,29.57,NaN,6.10,48.43,53.49,0.74,0.21,2.75,NaN,NaN
18,Ahmedabad,2015-01-19,NaN,NaN,2.51,26.88,27.45,NaN,2.51,50.03,49.48,0.26,0.02,2.80,NaN,NaN
19,Ahmedabad,2015-01-20,NaN,NaN,7.92,26.80,32.40,NaN,7.92,58.87,56.37,0.24,0.01,3.97,NaN,NaN

In [15]:
city_day['Date'] = pd.to_datetime(city_day['Date'])

In [16]:
city_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  datetime64[ns]
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 3.6+ MB

In [17]:
# 1. List of pollutants to clean (We leave AQI out for now)
pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']

# 2. Apply interpolation to each one
# We group by 'City' so we don't mix data from different cities
for col in pollutants:
    city_day[col] = city_day.groupby('City')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )

# 3. Check the result
print("Missing values after interpolation:")
print(city_day[pollutants].isnull().sum())

Missing values after interpolation:
PM2.5          0
PM10        2009
NO             0
NO2            0
NOx         1169
NH3         2009
CO             0
SO2            0
O3           162
Benzene     2732
Toluene     4010
Xylene     13047
dtype: int64

Most columns (like PM2.5, CO) went to 0 missing values. Some (like Xylene) still have some missing values. This happens if a city never measured Xylene in its history (so there is nothing to interpolate). We are not filling  those remaining ones with 0 later as they might actually convey the wrong message that xyelne or benzene were literally 0 (or not there) in the city.

In [18]:
import pandas as pd
import numpy as np

# 1. Helper function to get the text category (Bucket)
def get_aqi_bucket(aqi_value):
    if pd.isnull(aqi_value): return np.nan
    if aqi_value <= 50: return "Good"
    elif aqi_value <= 100: return "Satisfactory"
    elif aqi_value <= 200: return "Moderate"
    elif aqi_value <= 300: return "Poor"
    elif aqi_value <= 400: return "Very Poor"
    elif aqi_value > 400: return "Severe"
    else: return np.nan

# 2. The Main Formula to Calculate AQI
def calculate_aqi(row):
    # Indian National Air Quality Index (NAQI) Breakpoints
    breakpoints = {
        'PM2.5': [(0, 30, 0, 50), (30, 60, 51, 100), (60, 90, 101, 200), (90, 120, 201, 300), (120, 250, 301, 400), (250, 9999, 401, 500)],
        'PM10':  [(0, 50, 0, 50), (50, 100, 51, 100), (100, 250, 101, 200), (250, 350, 201, 300), (350, 430, 301, 400), (430, 9999, 401, 500)],
        'NO2':   [(0, 40, 0, 50), (40, 80, 51, 100), (80, 180, 101, 200), (180, 280, 201, 300), (280, 400, 301, 400), (400, 9999, 401, 500)],
        'SO2':   [(0, 40, 0, 50), (40, 80, 51, 100), (80, 380, 101, 200), (380, 800, 201, 300), (800, 1600, 301, 400), (1600, 9999, 401, 500)],
        'CO':    [(0, 1, 0, 50), (1, 2, 51, 100), (2, 10, 101, 200), (10, 17, 201, 300), (17, 34, 301, 400), (34, 9999, 401, 500)],
        'O3':    [(0, 50, 0, 50), (50, 100, 51, 100), (100, 168, 101, 200), (168, 208, 201, 300), (208, 748, 301, 400), (748, 9999, 401, 500)],
        'NH3':   [(0, 200, 0, 50), (200, 400, 51, 100), (400, 800, 101, 200), (800, 1200, 201, 300), (1200, 1800, 301, 400), (1800, 9999, 401, 500)]
    }
    
    aqi_list = []
    
    # Loop through each pollutant and calculate its specific sub-index
    for pollutant, ranges in breakpoints.items():
        if pollutant in row and not pd.isnull(row[pollutant]):
            concentration = row[pollutant]
            for (low, high, aqi_low, aqi_high) in ranges:
                if low <= concentration <= high:
                    # The formula: I = [(I_Hi - I_Lo) / (C_Hi - C_Lo)] * (C - C_Lo) + I_Lo
                    aqi = ((aqi_high - aqi_low) / (high - low)) * (concentration - low) + aqi_low
                    aqi_list.append(aqi)
                    break
    
    # The final AQI is the MAXIMUM of all sub-indices
    if aqi_list:
        return max(aqi_list)
    else:
        return np.nan

print("Functions defined successfully!")

Functions defined successfully!

In [19]:
# 1. Interpolate what we can (Standard Pollutants)
# We do NOT fill with 0. We only connect the dots where dots exist.
pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']

for col in pollutants:
    city_day[col] = city_day.groupby('City')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )

print("Interpolation done. Remaining gaps are genuine missing data.")

# 2. Check remaining nulls (Likely Lucknow's PM10 and the 14 cities' Xylene)
print(city_day[['PM10', 'Xylene']].isnull().sum())

# 3. Calculate AQI (The formula ignores NaNs automatically)
# Ensure you have the 'calculate_aqi' function defined from before
print("Calculating AQI...")
mask_missing_aqi = city_day['AQI'].isnull()
city_day.loc[mask_missing_aqi, 'AQI'] = city_day.loc[mask_missing_aqi].apply(calculate_aqi, axis=1)

# 4. Fill Bucket
city_day['AQI_Bucket'] = city_day['AQI'].apply(get_aqi_bucket)

print("Process Complete. No fake zeros added!")

Interpolation done. Remaining gaps are genuine missing data.
PM10       2009
Xylene    13047
dtype: int64
Calculating AQI...
Process Complete. No fake zeros added!

In [20]:
city_day.isnull().sum()

City              0
Date              0
PM2.5             0
PM10           2009
NO                0
NO2               0
NOx            1169
NH3            2009
CO                0
SO2               0
O3              162
Benzene        2732
Toluene        4010
Xylene        13047
AQI               0
AQI_Bucket        0
dtype: int64

In [21]:
city_day.head(20)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,73.24,141.54,0.920,18.22,17.15,NaN,0.920,27.64,133.36,0.00,0.02,0.00,149.568235,Moderate
1,Ahmedabad,2015-01-02,73.24,141.54,0.970,15.69,16.46,NaN,0.970,24.55,34.06,3.68,5.50,3.77,144.692000,Moderate
2,Ahmedabad,2015-01-03,73.24,141.54,17.400,19.30,29.70,NaN,17.400,29.07,30.70,6.80,16.40,2.25,303.329412,Very Poor
3,Ahmedabad,2015-01-04,73.24,141.54,1.700,18.48,17.97,NaN,1.700,18.59,36.08,4.43,10.14,1.00,144.692000,Moderate
4,Ahmedabad,2015-01-05,73.24,141.54,22.100,21.42,37.76,NaN,22.100,39.33,39.31,7.01,18.89,2.78,330.700000,Very Poor
5,Ahmedabad,2015-01-06,73.24,141.54,45.410,38.48,81.50,NaN,45.410,45.76,46.51,5.42,10.83,1.93,401.113356,Severe
6,Ahmedabad,2015-01-07,73.24,141.54,112.160,40.62,130.77,NaN,112.160,32.28,33.47,0.00,0.00,0.00,401.776502,Severe
7,Ahmedabad,2015-01-08,73.24,141.54,80.870,36.74,96.75,NaN,80.870,38.54,31.89,0.00,0.00,0.00,401.465643,Severe
8,Ahmedabad,2015-01-09,73.24,141.54,29.160,31.00,48.00,NaN,29.160,58.68,25.75,0.00,0.00,0.00,371.814118,Very Poor
9,Ahmedabad,2015-01-10,73.24,141.54,80.615,7.04,0.00,NaN,80.615,8.29,4.55,0.00,0.00,0.00,401.463109,Severe
10,Ahmedabad,2015-01-11,73.24,141.54,132.070,55.80,24.53,NaN,132.070,25.03,6.79,0.00,0.00,0.00,401.974303,Severe
11,Ahmedabad,2015-01-12,73.24,141.54,52.040,40.67,90.24,NaN,52.040,51.84,45.89,2.41,0.03,7.88,401.179223,Severe
12,Ahmedabad,2015-01-13,73.24,141.54,48.820,44.20,87.09,NaN,48.820,68.21,35.16,9.45,13.35,12.50,401.147233,Severe
13,Ahmedabad,2015-01-14,73.24,141.54,19.200,27.86,33.05,NaN,19.200,52.65,20.96,2.16,2.26,5.19,313.811765,Very Poor
14,Ahmedabad,2015-01-15,73.24,141.54,0.600,16.96,16.60,NaN,0.600,28.89,47.63,0.14,0.04,1.35,144.692000,Moderate
15,Ahmedabad,2015-01-16,73.24,141.54,1.630,21.72,22.86,NaN,1.630,38.27,46.03,0.35,0.05,2.01,144.692000,Moderate
16,Ahmedabad,2015-01-17,73.24,141.54,11.440,24.73,34.75,NaN,11.440,49.50,52.24,0.68,0.00,3.27,221.365714,Poor
17,Ahmedabad,2015-01-18,73.24,141.54,6.100,25.77,29.57,NaN,6.100,48.43,53.49,0.74,0.21,2.75,151.737500,Moderate
18,Ahmedabad,2015-01-19,73.24,141.54,2.510,26.88,27.45,NaN,2.510,50.03,49.48,0.26,0.02,2.80,144.692000,Moderate
19,Ahmedabad,2015-01-20,73.24,141.54,7.920,26.80,32.40,NaN,7.920,58.87,56.37,0.24,0.01,3.97,174.260000,Moderate

In [22]:
city_day.tail(20)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
29511,Visakhapatnam,2020-06-12,37.67,76.27,12.17,53.59,35.52,9.85,0.97,5.74,17.35,4.77,18.89,2.85,84.0,Satisfactory
29512,Visakhapatnam,2020-06-13,22.75,86.77,3.85,38.23,22.60,9.24,0.67,10.70,27.24,3.06,8.49,1.26,81.0,Satisfactory
29513,Visakhapatnam,2020-06-14,21.33,83.23,2.81,34.56,20.43,9.78,0.58,9.37,29.44,2.29,5.91,0.97,88.0,Satisfactory
29514,Visakhapatnam,2020-06-15,24.66,100.53,3.66,37.93,22.97,9.22,0.71,7.02,28.63,3.13,6.12,1.51,92.0,Satisfactory
29515,Visakhapatnam,2020-06-16,21.06,80.51,6.67,40.33,26.81,8.81,0.63,11.09,21.69,3.77,6.55,1.69,83.0,Satisfactory
29516,Visakhapatnam,2020-06-17,17.05,73.22,6.08,36.31,24.23,6.69,0.54,11.08,26.09,2.96,6.96,1.39,90.0,Satisfactory
29517,Visakhapatnam,2020-06-18,21.16,88.80,4.94,42.96,26.79,3.22,0.68,11.05,27.65,4.38,7.65,1.69,71.0,Satisfactory
29518,Visakhapatnam,2020-06-19,14.41,66.81,6.22,40.06,26.10,7.51,1.07,13.23,27.34,2.55,8.98,1.45,110.0,Moderate
29519,Visakhapatnam,2020-06-20,26.67,86.29,3.78,37.36,22.46,15.05,0.74,11.76,41.97,3.14,11.89,1.87,74.0,Satisfactory
29520,Visakhapatnam,2020-06-21,25.96,91.75,5.65,40.22,25.78,13.32,0.71,10.10,38.27,3.10,10.26,1.57,92.0,Satisfactory
29521,Visakhapatnam,2020-06-22,33.17,108.22,5.58,42.45,27.06,13.70,0.73,13.65,34.85,3.99,10.24,2.32,95.0,Satisfactory
29522,Visakhapatnam,2020-06-23,25.40,83.38,2.76,34.09,19.92,13.13,0.54,10.40,43.27,2.88,12.03,1.33,100.0,Satisfactory
29523,Visakhapatnam,2020-06-24,34.36,90.90,1.22,23.38,13.12,14.45,0.56,10.92,35.12,2.99,3.15,1.60,86.0,Satisfactory
29524,Visakhapatnam,2020-06-25,13.45,58.54,2.30,21.60,13.09,12.27,0.41,8.19,29.38,1.28,5.64,0.92,77.0,Satisfactory
29525,Visakhapatnam,2020-06-26,7.63,32.27,5.91,23.27,17.19,11.15,0.46,6.87,19.90,1.45,5.37,1.45,47.0,Good
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,0.00,0.00,0.00,50.0,Good

In [23]:
city_day['NH3'].isnull().sum()

np.int64(2009)

In [24]:
# Check which cities have ZERO NH3 data
print(city_day.groupby('City')['NH3'].count())

City
Ahmedabad                0
Aizawl                 113
Amaravati              951
Amritsar              1221
Bengaluru             2009
Bhopal                 289
Brajrajnagar           938
Chandigarh             304
Chennai               2009
Coimbatore             386
Delhi                 2009
Ernakulam              162
Gurugram              1679
Guwahati               502
Hyderabad             2006
Jaipur                1114
Jorapokhar            1169
Kochi                  162
Kolkata                814
Lucknow               2009
Mumbai                2009
Patna                 1858
Shillong               310
Talcher                925
Thiruvananthapuram    1112
Visakhapatnam         1462
Name: NH3, dtype: int64

In [25]:
city_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707875 entries, 0 to 707874
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   City        707875 non-null  object
 1   Datetime    707875 non-null  object
 2   PM2.5       562787 non-null  float64
 3   PM10        411138 non-null  float64
 4   NO          591243 non-null  float64
 5   NO2         590753 non-null  float64
 6   NOx         584651 non-null  float64
 7   NH3         435333 non-null  float64
 8   CO          621358 non-null  float64
 9   SO2         577502 non-null  float64
 10  O3          578667 non-null  float64
 11  Benzene     544229 non-null  float64
 12  Toluene     487268 non-null  float64
 13  Xylene      252046 non-null  float64
 14  AQI         578795 non-null  float64
 15  AQI_Bucket  578795 non-null  object
dtypes: float64(13), object(3)
memory usage: 86.4+ MB

In [26]:
city_hour.head(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01 01:00:00,NaN,NaN,1.00,40.01,36.37,NaN,1.00,122.07,NaN,0.0,0.00,0.0,NaN,NaN
1,Ahmedabad,2015-01-01 02:00:00,NaN,NaN,0.02,27.75,19.73,NaN,0.02,85.90,NaN,0.0,0.00,0.0,NaN,NaN
2,Ahmedabad,2015-01-01 03:00:00,NaN,NaN,0.08,19.32,11.08,NaN,0.08,52.83,NaN,0.0,0.00,0.0,NaN,NaN
3,Ahmedabad,2015-01-01 04:00:00,NaN,NaN,0.30,16.45,9.20,NaN,0.30,39.53,153.58,0.0,0.00,0.0,NaN,NaN
4,Ahmedabad,2015-01-01 05:00:00,NaN,NaN,0.12,14.90,7.85,NaN,0.12,32.63,NaN,0.0,0.00,0.0,NaN,NaN
5,Ahmedabad,2015-01-01 06:00:00,NaN,NaN,0.33,15.95,10.82,NaN,0.33,29.87,64.25,0.0,0.00,0.0,NaN,NaN
6,Ahmedabad,2015-01-01 07:00:00,NaN,NaN,0.45,15.94,12.47,NaN,0.45,27.41,191.96,0.0,0.00,0.0,NaN,NaN
7,Ahmedabad,2015-01-01 08:00:00,NaN,NaN,1.03,16.66,16.48,NaN,1.03,20.92,177.21,0.0,0.00,0.0,NaN,NaN
8,Ahmedabad,2015-01-01 09:00:00,NaN,NaN,1.47,16.25,18.02,NaN,1.47,16.45,122.08,0.0,0.00,0.0,NaN,NaN
9,Ahmedabad,2015-01-01 10:00:00,NaN,NaN,2.05,13.78,16.08,NaN,2.05,15.14,NaN,0.0,0.00,0.0,NaN,NaN
10,Ahmedabad,2015-01-01 11:00:00,NaN,NaN,2.27,13.87,16.73,NaN,2.27,14.12,99.17,0.0,0.00,0.0,NaN,NaN
11,Ahmedabad,2015-01-01 12:00:00,NaN,NaN,1.73,12.87,14.63,NaN,1.73,13.26,91.67,0.0,0.00,0.0,NaN,NaN
12,Ahmedabad,2015-01-01 13:00:00,NaN,NaN,1.72,14.15,15.55,NaN,1.72,17.20,95.92,0.0,0.00,0.0,NaN,NaN
13,Ahmedabad,2015-01-01 14:00:00,NaN,NaN,1.85,15.74,17.62,NaN,1.85,18.78,NaN,0.0,0.00,0.0,NaN,NaN
14,Ahmedabad,2015-01-01 15:00:00,NaN,NaN,0.95,15.94,16.18,NaN,0.95,19.16,NaN,0.0,0.00,0.0,NaN,NaN
15,Ahmedabad,2015-01-01 16:00:00,NaN,NaN,0.87,17.28,18.32,NaN,0.87,17.83,NaN,0.0,0.00,0.0,NaN,NaN
16,Ahmedabad,2015-01-01 17:00:00,NaN,NaN,0.80,19.04,20.00,NaN,0.80,16.14,187.62,0.0,0.00,0.0,NaN,NaN
17,Ahmedabad,2015-01-01 18:00:00,NaN,NaN,0.47,21.24,22.70,NaN,0.47,11.93,NaN,0.0,0.00,0.0,NaN,NaN
18,Ahmedabad,2015-01-01 19:00:00,NaN,NaN,0.53,25.63,27.42,NaN,0.53,14.99,NaN,0.0,0.33,0.0,NaN,NaN
19,Ahmedabad,2015-01-01 20:00:00,NaN,NaN,0.47,16.22,16.00,NaN,0.47,13.66,187.42,0.0,0.23,0.0,NaN,NaN

In [27]:
city_hour.isnull().sum()

City               0
Datetime           0
PM2.5         145088
PM10          296737
NO            116632
NO2           117122
NOx           123224
NH3           272542
CO             86517
SO2           130373
O3            129208
Benzene       163646
Toluene       220607
Xylene        455829
AQI           129080
AQI_Bucket    129080
dtype: int64

In [28]:
city_hour.tail(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
707855,Visakhapatnam,2020-06-30 05:00:00,13.50,44.75,6.60,35.15,24.05,7.90,0.23,7.95,23.35,0.0,0.0,0.0,55.0,Satisfactory
707856,Visakhapatnam,2020-06-30 06:00:00,15.00,50.00,15.45,36.88,32.20,5.92,0.35,3.60,14.62,0.0,0.0,0.0,54.0,Satisfactory
707857,Visakhapatnam,2020-06-30 07:00:00,32.00,77.00,9.55,33.05,25.35,3.52,0.53,0.90,16.58,0.0,0.0,0.0,54.0,Satisfactory
707858,Visakhapatnam,2020-06-30 08:00:00,37.00,76.00,4.15,32.55,20.70,4.93,0.64,1.90,15.83,0.0,0.0,0.0,52.0,Satisfactory
707859,Visakhapatnam,2020-06-30 09:00:00,27.75,68.50,6.78,36.62,24.95,10.68,0.73,13.85,27.75,0.0,0.0,0.0,51.0,Satisfactory
707860,Visakhapatnam,2020-06-30 10:00:00,9.00,55.50,9.25,44.40,31.12,17.98,0.78,24.67,24.40,0.0,0.0,0.0,51.0,Satisfactory
707861,Visakhapatnam,2020-06-30 11:00:00,12.75,66.50,5.45,54.60,33.45,22.28,0.89,39.70,29.62,0.0,0.0,0.0,51.0,Satisfactory
707862,Visakhapatnam,2020-06-30 12:00:00,21.50,83.00,3.85,31.35,19.80,28.50,0.66,17.80,35.77,0.0,0.0,0.0,51.0,Satisfactory
707863,Visakhapatnam,2020-06-30 13:00:00,12.75,45.00,0.55,17.20,9.32,9.12,0.11,10.82,45.80,0.0,0.0,0.0,50.0,Good
707864,Visakhapatnam,2020-06-30 14:00:00,10.75,36.75,1.10,17.75,10.28,4.65,0.34,4.38,50.73,0.0,0.0,0.0,51.0,Satisfactory
707865,Visakhapatnam,2020-06-30 15:00:00,15.75,30.25,0.95,13.75,8.07,4.67,0.30,2.90,41.55,0.0,0.0,0.0,51.0,Satisfactory
707866,Visakhapatnam,2020-06-30 16:00:00,14.00,29.50,1.77,20.70,12.45,8.08,0.45,7.12,39.23,0.0,0.0,0.0,51.0,Satisfactory
707867,Visakhapatnam,2020-06-30 17:00:00,9.75,24.25,2.88,23.85,15.02,12.23,0.57,8.45,34.78,0.0,0.0,0.0,51.0,Satisfactory
707868,Visakhapatnam,2020-06-30 18:00:00,6.50,24.75,2.25,23.38,13.68,10.60,0.66,5.80,33.55,NaN,NaN,NaN,51.0,Satisfactory
707869,Visakhapatnam,2020-06-30 19:00:00,8.25,33.25,0.35,24.05,13.05,5.55,0.44,1.85,41.38,NaN,NaN,NaN,51.0,Satisfactory
707870,Visakhapatnam,2020-06-30 20:00:00,9.50,36.00,2.75,25.57,15.85,4.57,0.62,NaN,27.75,NaN,NaN,NaN,51.0,Satisfactory
707871,Visakhapatnam,2020-06-30 21:00:00,17.25,49.25,3.62,33.20,20.62,3.78,0.76,2.02,25.58,NaN,NaN,NaN,51.0,Satisfactory
707872,Visakhapatnam,2020-06-30 22:00:00,36.00,71.00,2.20,30.80,18.20,3.67,0.58,1.77,26.15,NaN,NaN,NaN,50.0,Good
707873,Visakhapatnam,2020-06-30 23:00:00,15.75,63.00,1.02,28.90,16.00,3.80,0.49,0.75,15.82,NaN,NaN,NaN,50.0,Good
707874,Visakhapatnam,2020-07-01 00:00:00,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

In [29]:
# Convert to datetime objects
city_hour['Datetime'] = pd.to_datetime(city_hour['Datetime'])

# Extract Date and Time into separate columns
city_hour['Date'] = city_hour['Datetime'].dt.date
city_hour['Time'] = city_hour['Datetime'].dt.time

In [30]:
city_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707875 entries, 0 to 707874
Data columns (total 18 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   City        707875 non-null  object
 1   Datetime    707875 non-null  datetime64[ns]
 2   PM2.5       562787 non-null  float64
 3   PM10        411138 non-null  float64
 4   NO          591243 non-null  float64
 5   NO2         590753 non-null  float64
 6   NOx         584651 non-null  float64
 7   NH3         435333 non-null  float64
 8   CO          621358 non-null  float64
 9   SO2         577502 non-null  float64
 10  O3          578667 non-null  float64
 11  Benzene     544229 non-null  float64
 12  Toluene     487268 non-null  float64
 13  Xylene      252046 non-null  float64
 14  AQI         578795 non-null  float64
 15  AQI_Bucket  578795 non-null  object
 16  Date        707875 non-null  object
 17  Time        707875 non-null  object
dtypes: datetime64[ns](1), float64(13), object(4)
memory usage: 97.2+ MB

In [31]:
city_hour.sort_values(by=['City', 'Datetime'], inplace=True)

In [32]:
city_hour.head(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Date,Time
0,Ahmedabad,2015-01-01 01:00:00,NaN,NaN,1.00,40.01,36.37,NaN,1.00,122.07,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,01:00:00
1,Ahmedabad,2015-01-01 02:00:00,NaN,NaN,0.02,27.75,19.73,NaN,0.02,85.90,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,02:00:00
2,Ahmedabad,2015-01-01 03:00:00,NaN,NaN,0.08,19.32,11.08,NaN,0.08,52.83,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,03:00:00
3,Ahmedabad,2015-01-01 04:00:00,NaN,NaN,0.30,16.45,9.20,NaN,0.30,39.53,153.58,0.0,0.00,0.0,NaN,NaN,2015-01-01,04:00:00
4,Ahmedabad,2015-01-01 05:00:00,NaN,NaN,0.12,14.90,7.85,NaN,0.12,32.63,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,05:00:00
5,Ahmedabad,2015-01-01 06:00:00,NaN,NaN,0.33,15.95,10.82,NaN,0.33,29.87,64.25,0.0,0.00,0.0,NaN,NaN,2015-01-01,06:00:00
6,Ahmedabad,2015-01-01 07:00:00,NaN,NaN,0.45,15.94,12.47,NaN,0.45,27.41,191.96,0.0,0.00,0.0,NaN,NaN,2015-01-01,07:00:00
7,Ahmedabad,2015-01-01 08:00:00,NaN,NaN,1.03,16.66,16.48,NaN,1.03,20.92,177.21,0.0,0.00,0.0,NaN,NaN,2015-01-01,08:00:00
8,Ahmedabad,2015-01-01 09:00:00,NaN,NaN,1.47,16.25,18.02,NaN,1.47,16.45,122.08,0.0,0.00,0.0,NaN,NaN,2015-01-01,09:00:00
9,Ahmedabad,2015-01-01 10:00:00,NaN,NaN,2.05,13.78,16.08,NaN,2.05,15.14,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,10:00:00
10,Ahmedabad,2015-01-01 11:00:00,NaN,NaN,2.27,13.87,16.73,NaN,2.27,14.12,99.17,0.0,0.00,0.0,NaN,NaN,2015-01-01,11:00:00
11,Ahmedabad,2015-01-01 12:00:00,NaN,NaN,1.73,12.87,14.63,NaN,1.73,13.26,91.67,0.0,0.00,0.0,NaN,NaN,2015-01-01,12:00:00
12,Ahmedabad,2015-01-01 13:00:00,NaN,NaN,1.72,14.15,15.55,NaN,1.72,17.20,95.92,0.0,0.00,0.0,NaN,NaN,2015-01-01,13:00:00
13,Ahmedabad,2015-01-01 14:00:00,NaN,NaN,1.85,15.74,17.62,NaN,1.85,18.78,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,14:00:00
14,Ahmedabad,2015-01-01 15:00:00,NaN,NaN,0.95,15.94,16.18,NaN,0.95,19.16,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,15:00:00
15,Ahmedabad,2015-01-01 16:00:00,NaN,NaN,0.87,17.28,18.32,NaN,0.87,17.83,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,16:00:00
16,Ahmedabad,2015-01-01 17:00:00,NaN,NaN,0.80,19.04,20.00,NaN,0.80,16.14,187.62,0.0,0.00,0.0,NaN,NaN,2015-01-01,17:00:00
17,Ahmedabad,2015-01-01 18:00:00,NaN,NaN,0.47,21.24,22.70,NaN,0.47,11.93,NaN,0.0,0.00,0.0,NaN,NaN,2015-01-01,18:00:00
18,Ahmedabad,2015-01-01 19:00:00,NaN,NaN,0.53,25.63,27.42,NaN,0.53,14.99,NaN,0.0,0.33,0.0,NaN,NaN,2015-01-01,19:00:00
19,Ahmedabad,2015-01-01 20:00:00,NaN,NaN,0.47,16.22,16.00,NaN,0.47,13.66,187.42,0.0,0.23,0.0,NaN,NaN,2015-01-01,20:00:00

In [33]:
# Check how many zeros exist in every single column
print((city_hour == 0).sum())

City               0
Datetime           0
PM2.5              0
PM10               0
NO                 0
NO2                0
NOx            19811
NH3                0
CO             66088
SO2                0
O3                 0
Benzene       118727
Toluene        89705
Xylene         49350
AQI                0
AQI_Bucket         0
Date               0
Time               0
dtype: int64

In [34]:
city_hour.isnull().sum()

City               0
Datetime           0
PM2.5         145088
PM10          296737
NO            116632
NO2           117122
NOx           123224
NH3           272542
CO             86517
SO2           130373
O3            129208
Benzene       163646
Toluene       220607
Xylene        455829
AQI           129080
AQI_Bucket    129080
Date               0
Time               0
dtype: int64

In [40]:
import numpy as np

# 1. Fix "Impossible" Zeros (Particulate Matter only)
# We assume dust is never 0.00. Everything else (CO, SO2) can be 0.
city_hour['PM2.5'] = city_hour['PM2.5'].replace(0, np.nan)
city_hour['PM10'] = city_hour['PM10'].replace(0, np.nan)

# 2. Interpolate ALL missing values (Linear)
# This fills the "Impossible" zeros we just deleted, AND the original gaps.
# We limit the fill to 12 hours. If a sensor is dead for >12 hours, we leave it blank.
cols_to_fix = ['PM2.5', 'PM10', 'NO2', 'NH3', 'SO2', 'CO', 'O3']
city_hour[cols_to_fix] = city_hour[cols_to_fix].interpolate(method='linear', limit=12, limit_direction='both')

# 3. Handling the remaining Zeros in CO (The 66k zeros)
# We leave them alone. 
# But to prevent math errors later (like dividing by zero), 
# we can swap them with a tiny number if needed, or just let them be.
# If your AQI calculation crashes on 0, run this line:
# df['CO'] = df['CO'].replace(0, 0.01)

In [41]:
city_hour.head()

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Date,Time
0,Ahmedabad,2015-01-01 01:00:00,NaN,NaN,1.00,40.01,36.37,NaN,1.00,122.07,153.580,0.0,0.0,0.0,NaN,NaN,2015-01-01,01:00:00
1,Ahmedabad,2015-01-01 02:00:00,NaN,NaN,0.02,27.75,19.73,NaN,0.02,85.90,153.580,0.0,0.0,0.0,NaN,NaN,2015-01-01,02:00:00
2,Ahmedabad,2015-01-01 03:00:00,NaN,NaN,0.08,19.32,11.08,NaN,0.08,52.83,153.580,0.0,0.0,0.0,NaN,NaN,2015-01-01,03:00:00
3,Ahmedabad,2015-01-01 04:00:00,NaN,NaN,0.30,16.45,9.20,NaN,0.30,39.53,153.580,0.0,0.0,0.0,NaN,NaN,2015-01-01,04:00:00
4,Ahmedabad,2015-01-01 05:00:00,NaN,NaN,0.12,14.90,7.85,NaN,0.12,32.63,108.915,0.0,0.0,0.0,NaN,NaN,2015-01-01,05:00:00

In [43]:
# --- STEP 3.5: Handle the Start/End Gaps (Backfill/Forwardfill) ---

# Interpolation works for gaps in the middle, but can't fix the very first row 
# if it's empty (because there's no previous value to connect to).

cols_to_fix = ['PM2.5', 'PM10', 'NO2', 'NH3', 'SO2', 'CO', 'O3']

# 1. Fill the start of the file with the first valid number found (Backfill)
city_hour[cols_to_fix] = city_hour[cols_to_fix].fillna(method='bfill')

# 2. Fill the end of the file with the last valid number found (Forwardfill)
city_hour[cols_to_fix] = city_hour[cols_to_fix].fillna(method='ffill')

# 3. Verify that NaNs are truly gone
print("Remaining NaNs in PM2.5:", city_hour['PM2.5'].isnull().sum())
print("Remaining NaNs in PM10:", city_hour['PM10'].isnull().sum())

Remaining NaNs in PM2.5: 0
Remaining NaNs in PM10: 0

C:\Users\Ankitha Hathwar\AppData\Local\Temp\ipykernel_10704\1009207371.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  city_hour[cols_to_fix] = city_hour[cols_to_fix].fillna(method='bfill')
C:\Users\Ankitha Hathwar\AppData\Local\Temp\ipykernel_10704\1009207371.py:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  city_hour[cols_to_fix] = city_hour[cols_to_fix].fillna(method='ffill')

In [44]:
city_hour.head(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Date,Time
0,Ahmedabad,2015-01-01 01:00:00,36.6,120.06,1.00,40.01,36.37,19.88,1.00,122.07,153.580000,0.0,0.00,0.0,NaN,NaN,2015-01-01,01:00:00
1,Ahmedabad,2015-01-01 02:00:00,36.6,120.06,0.02,27.75,19.73,19.88,0.02,85.90,153.580000,0.0,0.00,0.0,NaN,NaN,2015-01-01,02:00:00
2,Ahmedabad,2015-01-01 03:00:00,36.6,120.06,0.08,19.32,11.08,19.88,0.08,52.83,153.580000,0.0,0.00,0.0,NaN,NaN,2015-01-01,03:00:00
3,Ahmedabad,2015-01-01 04:00:00,36.6,120.06,0.30,16.45,9.20,19.88,0.30,39.53,153.580000,0.0,0.00,0.0,NaN,NaN,2015-01-01,04:00:00
4,Ahmedabad,2015-01-01 05:00:00,36.6,120.06,0.12,14.90,7.85,19.88,0.12,32.63,108.915000,0.0,0.00,0.0,NaN,NaN,2015-01-01,05:00:00
5,Ahmedabad,2015-01-01 06:00:00,36.6,120.06,0.33,15.95,10.82,19.88,0.33,29.87,64.250000,0.0,0.00,0.0,NaN,NaN,2015-01-01,06:00:00
6,Ahmedabad,2015-01-01 07:00:00,36.6,120.06,0.45,15.94,12.47,19.88,0.45,27.41,191.960000,0.0,0.00,0.0,NaN,NaN,2015-01-01,07:00:00
7,Ahmedabad,2015-01-01 08:00:00,36.6,120.06,1.03,16.66,16.48,19.88,1.03,20.92,177.210000,0.0,0.00,0.0,NaN,NaN,2015-01-01,08:00:00
8,Ahmedabad,2015-01-01 09:00:00,36.6,120.06,1.47,16.25,18.02,19.88,1.47,16.45,122.080000,0.0,0.00,0.0,NaN,NaN,2015-01-01,09:00:00
9,Ahmedabad,2015-01-01 10:00:00,36.6,120.06,2.05,13.78,16.08,19.88,2.05,15.14,110.625000,0.0,0.00,0.0,NaN,NaN,2015-01-01,10:00:00
10,Ahmedabad,2015-01-01 11:00:00,36.6,120.06,2.27,13.87,16.73,19.88,2.27,14.12,99.170000,0.0,0.00,0.0,NaN,NaN,2015-01-01,11:00:00
11,Ahmedabad,2015-01-01 12:00:00,36.6,120.06,1.73,12.87,14.63,19.88,1.73,13.26,91.670000,0.0,0.00,0.0,NaN,NaN,2015-01-01,12:00:00
12,Ahmedabad,2015-01-01 13:00:00,36.6,120.06,1.72,14.15,15.55,19.88,1.72,17.20,95.920000,0.0,0.00,0.0,NaN,NaN,2015-01-01,13:00:00
13,Ahmedabad,2015-01-01 14:00:00,36.6,120.06,1.85,15.74,17.62,19.88,1.85,18.78,118.845000,0.0,0.00,0.0,NaN,NaN,2015-01-01,14:00:00
14,Ahmedabad,2015-01-01 15:00:00,36.6,120.06,0.95,15.94,16.18,19.88,0.95,19.16,141.770000,0.0,0.00,0.0,NaN,NaN,2015-01-01,15:00:00
15,Ahmedabad,2015-01-01 16:00:00,36.6,120.06,0.87,17.28,18.32,19.88,0.87,17.83,164.695000,0.0,0.00,0.0,NaN,NaN,2015-01-01,16:00:00
16,Ahmedabad,2015-01-01 17:00:00,36.6,120.06,0.80,19.04,20.00,19.88,0.80,16.14,187.620000,0.0,0.00,0.0,NaN,NaN,2015-01-01,17:00:00
17,Ahmedabad,2015-01-01 18:00:00,36.6,120.06,0.47,21.24,22.70,19.88,0.47,11.93,187.553333,0.0,0.00,0.0,NaN,NaN,2015-01-01,18:00:00
18,Ahmedabad,2015-01-01 19:00:00,36.6,120.06,0.53,25.63,27.42,19.88,0.53,14.99,187.486667,0.0,0.33,0.0,NaN,NaN,2015-01-01,19:00:00
19,Ahmedabad,2015-01-01 20:00:00,36.6,120.06,0.47,16.22,16.00,19.88,0.47,13.66,187.420000,0.0,0.23,0.0,NaN,NaN,2015-01-01,20:00:00

In [45]:
city_hour.tail(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Date,Time
707855,Visakhapatnam,2020-06-30 05:00:00,13.50,44.75,6.60,35.15,24.05,7.90,0.23,7.950,23.35,0.0,0.0,0.0,55.0,Satisfactory,2020-06-30,05:00:00
707856,Visakhapatnam,2020-06-30 06:00:00,15.00,50.00,15.45,36.88,32.20,5.92,0.35,3.600,14.62,0.0,0.0,0.0,54.0,Satisfactory,2020-06-30,06:00:00
707857,Visakhapatnam,2020-06-30 07:00:00,32.00,77.00,9.55,33.05,25.35,3.52,0.53,0.900,16.58,0.0,0.0,0.0,54.0,Satisfactory,2020-06-30,07:00:00
707858,Visakhapatnam,2020-06-30 08:00:00,37.00,76.00,4.15,32.55,20.70,4.93,0.64,1.900,15.83,0.0,0.0,0.0,52.0,Satisfactory,2020-06-30,08:00:00
707859,Visakhapatnam,2020-06-30 09:00:00,27.75,68.50,6.78,36.62,24.95,10.68,0.73,13.850,27.75,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,09:00:00
707860,Visakhapatnam,2020-06-30 10:00:00,9.00,55.50,9.25,44.40,31.12,17.98,0.78,24.670,24.40,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,10:00:00
707861,Visakhapatnam,2020-06-30 11:00:00,12.75,66.50,5.45,54.60,33.45,22.28,0.89,39.700,29.62,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,11:00:00
707862,Visakhapatnam,2020-06-30 12:00:00,21.50,83.00,3.85,31.35,19.80,28.50,0.66,17.800,35.77,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,12:00:00
707863,Visakhapatnam,2020-06-30 13:00:00,12.75,45.00,0.55,17.20,9.32,9.12,0.11,10.820,45.80,0.0,0.0,0.0,50.0,Good,2020-06-30,13:00:00
707864,Visakhapatnam,2020-06-30 14:00:00,10.75,36.75,1.10,17.75,10.28,4.65,0.34,4.380,50.73,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,14:00:00
707865,Visakhapatnam,2020-06-30 15:00:00,15.75,30.25,0.95,13.75,8.07,4.67,0.30,2.900,41.55,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,15:00:00
707866,Visakhapatnam,2020-06-30 16:00:00,14.00,29.50,1.77,20.70,12.45,8.08,0.45,7.120,39.23,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,16:00:00
707867,Visakhapatnam,2020-06-30 17:00:00,9.75,24.25,2.88,23.85,15.02,12.23,0.57,8.450,34.78,0.0,0.0,0.0,51.0,Satisfactory,2020-06-30,17:00:00
707868,Visakhapatnam,2020-06-30 18:00:00,6.50,24.75,2.25,23.38,13.68,10.60,0.66,5.800,33.55,NaN,NaN,NaN,51.0,Satisfactory,2020-06-30,18:00:00
707869,Visakhapatnam,2020-06-30 19:00:00,8.25,33.25,0.35,24.05,13.05,5.55,0.44,1.850,41.38,NaN,NaN,NaN,51.0,Satisfactory,2020-06-30,19:00:00
707870,Visakhapatnam,2020-06-30 20:00:00,9.50,36.00,2.75,25.57,15.85,4.57,0.62,1.935,27.75,NaN,NaN,NaN,51.0,Satisfactory,2020-06-30,20:00:00
707871,Visakhapatnam,2020-06-30 21:00:00,17.25,49.25,3.62,33.20,20.62,3.78,0.76,2.020,25.58,NaN,NaN,NaN,51.0,Satisfactory,2020-06-30,21:00:00
707872,Visakhapatnam,2020-06-30 22:00:00,36.00,71.00,2.20,30.80,18.20,3.67,0.58,1.770,26.15,NaN,NaN,NaN,50.0,Good,2020-06-30,22:00:00
707873,Visakhapatnam,2020-06-30 23:00:00,15.75,63.00,1.02,28.90,16.00,3.80,0.49,0.750,15.82,NaN,NaN,NaN,50.0,Good,2020-06-30,23:00:00
707874,Visakhapatnam,2020-07-01 00:00:00,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.100,17.05,NaN,NaN,NaN,50.0,Good,2020-07-01,00:00:00

In [46]:
print((city_hour == 0).sum())

City               0
Datetime           0
PM2.5              0
PM10               0
NO                 0
NO2                0
NOx            19811
NH3                0
CO             78096
SO2                0
O3                 0
Benzene       118727
Toluene        89705
Xylene         49350
AQI                0
AQI_Bucket         0
Date               0
Time               0
dtype: int64

In [49]:
city_day.head(20)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,73.24,141.54,0.920,18.22,17.15,NaN,0.920,27.64,133.36,0.00,0.02,0.00,149.568235,Moderate
1,Ahmedabad,2015-01-02,73.24,141.54,0.970,15.69,16.46,NaN,0.970,24.55,34.06,3.68,5.50,3.77,144.692000,Moderate
2,Ahmedabad,2015-01-03,73.24,141.54,17.400,19.30,29.70,NaN,17.400,29.07,30.70,6.80,16.40,2.25,303.329412,Very Poor
3,Ahmedabad,2015-01-04,73.24,141.54,1.700,18.48,17.97,NaN,1.700,18.59,36.08,4.43,10.14,1.00,144.692000,Moderate
4,Ahmedabad,2015-01-05,73.24,141.54,22.100,21.42,37.76,NaN,22.100,39.33,39.31,7.01,18.89,2.78,330.700000,Very Poor
5,Ahmedabad,2015-01-06,73.24,141.54,45.410,38.48,81.50,NaN,45.410,45.76,46.51,5.42,10.83,1.93,401.113356,Severe
6,Ahmedabad,2015-01-07,73.24,141.54,112.160,40.62,130.77,NaN,112.160,32.28,33.47,0.00,0.00,0.00,401.776502,Severe
7,Ahmedabad,2015-01-08,73.24,141.54,80.870,36.74,96.75,NaN,80.870,38.54,31.89,0.00,0.00,0.00,401.465643,Severe
8,Ahmedabad,2015-01-09,73.24,141.54,29.160,31.00,48.00,NaN,29.160,58.68,25.75,0.00,0.00,0.00,371.814118,Very Poor
9,Ahmedabad,2015-01-10,73.24,141.54,80.615,7.04,0.00,NaN,80.615,8.29,4.55,0.00,0.00,0.00,401.463109,Severe
10,Ahmedabad,2015-01-11,73.24,141.54,132.070,55.80,24.53,NaN,132.070,25.03,6.79,0.00,0.00,0.00,401.974303,Severe
11,Ahmedabad,2015-01-12,73.24,141.54,52.040,40.67,90.24,NaN,52.040,51.84,45.89,2.41,0.03,7.88,401.179223,Severe
12,Ahmedabad,2015-01-13,73.24,141.54,48.820,44.20,87.09,NaN,48.820,68.21,35.16,9.45,13.35,12.50,401.147233,Severe
13,Ahmedabad,2015-01-14,73.24,141.54,19.200,27.86,33.05,NaN,19.200,52.65,20.96,2.16,2.26,5.19,313.811765,Very Poor
14,Ahmedabad,2015-01-15,73.24,141.54,0.600,16.96,16.60,NaN,0.600,28.89,47.63,0.14,0.04,1.35,144.692000,Moderate
15,Ahmedabad,2015-01-16,73.24,141.54,1.630,21.72,22.86,NaN,1.630,38.27,46.03,0.35,0.05,2.01,144.692000,Moderate
16,Ahmedabad,2015-01-17,73.24,141.54,11.440,24.73,34.75,NaN,11.440,49.50,52.24,0.68,0.00,3.27,221.365714,Poor
17,Ahmedabad,2015-01-18,73.24,141.54,6.100,25.77,29.57,NaN,6.100,48.43,53.49,0.74,0.21,2.75,151.737500,Moderate
18,Ahmedabad,2015-01-19,73.24,141.54,2.510,26.88,27.45,NaN,2.510,50.03,49.48,0.26,0.02,2.80,144.692000,Moderate
19,Ahmedabad,2015-01-20,73.24,141.54,7.920,26.80,32.40,NaN,7.920,58.87,56.37,0.24,0.01,3.97,174.260000,Moderate

In [50]:
import numpy as np
import pandas as pd

# --- STEP 1: Define the Formulas (The Recipes) ---
# We define these right here so Python definitely knows them.

def get_PM25_subindex(x):
    if pd.isnull(x): return 0
    if x <= 30: return x * 50 / 30
    elif x <= 60: return 50 + (x - 30) * 50 / 30
    elif x <= 90: return 100 + (x - 60) * 100 / 30
    elif x <= 120: return 200 + (x - 90) * 100 / 30
    elif x <= 250: return 300 + (x - 120) * 100 / 130
    elif x > 250: return 400 + (x - 250) * 100 / 130
    else: return 0

def get_PM10_subindex(x):
    if pd.isnull(x): return 0
    if x <= 50: return x
    elif x <= 100: return x
    elif x <= 250: return 100 + (x - 100) * 100 / 150
    elif x <= 350: return 200 + (x - 250) * 100 / 100
    elif x <= 430: return 300 + (x - 350) * 100 / 80
    elif x > 430: return 400 + (x - 430) * 100 / 80
    else: return 0

def get_SO2_subindex(x):
    if pd.isnull(x): return 0
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 380: return 100 + (x - 80) * 100 / 300
    elif x <= 800: return 200 + (x - 380) * 100 / 420
    elif x <= 1600: return 300 + (x - 800) * 100 / 800
    elif x > 1600: return 400 + (x - 1600) * 100 / 800
    else: return 0

def get_NOx_subindex(x):
    if pd.isnull(x): return 0
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 180: return 100 + (x - 80) * 100 / 100
    elif x <= 280: return 200 + (x - 180) * 100 / 100
    elif x <= 400: return 300 + (x - 280) * 100 / 120
    elif x > 400: return 400 + (x - 400) * 100 / 120
    else: return 0

def get_NH3_subindex(x):
    if pd.isnull(x): return 0
    if x <= 200: return x * 50 / 200
    elif x <= 400: return 50 + (x - 200) * 50 / 200
    elif x <= 800: return 100 + (x - 400) * 100 / 400
    elif x <= 1200: return 200 + (x - 800) * 100 / 400
    elif x <= 1800: return 300 + (x - 1200) * 100 / 600
    elif x > 1800: return 400 + (x - 1800) * 100 / 600
    else: return 0

def get_CO_subindex(x):
    if pd.isnull(x): return 0
    if x <= 1: return x * 50 / 1
    elif x <= 2: return 50 + (x - 1) * 50 / 1
    elif x <= 10: return 100 + (x - 2) * 100 / 8
    elif x <= 17: return 200 + (x - 10) * 100 / 7
    elif x <= 34: return 300 + (x - 17) * 100 / 17
    elif x > 34: return 400 + (x - 34) * 100 / 17
    else: return 0

def get_O3_subindex(x):
    if pd.isnull(x): return 0
    if x <= 50: return x * 50 / 50
    elif x <= 100: return 50 + (x - 50) * 50 / 50
    elif x <= 168: return 100 + (x - 100) * 100 / 68
    elif x <= 208: return 200 + (x - 168) * 100 / 40
    elif x <= 748: return 300 + (x - 208) * 100 / 539
    elif x > 748: return 400 + (x - 748) * 100 / 539
    else: return 0

def get_aqi_bucket(x):
    if pd.isnull(x): return 'Unknown'
    if x <= 50: return 'Good'
    elif x <= 100: return 'Satisfactory'
    elif x <= 200: return 'Moderate'
    elif x <= 300: return 'Poor'
    elif x <= 400: return 'Very Poor'
    else: return 'Severe'

# --- STEP 2: Calculate Sub-Indices for city_hour ---
# We make new helper columns first
print("Calculating sub-indices...")
city_hour['PM2.5_SubIndex'] = city_hour['PM2.5'].apply(lambda x: get_PM25_subindex(x))
city_hour['PM10_SubIndex'] = city_hour['PM10'].apply(lambda x: get_PM10_subindex(x))
city_hour['SO2_SubIndex'] = city_hour['SO2'].apply(lambda x: get_SO2_subindex(x))
city_hour['NOx_SubIndex'] = city_hour['NOx'].apply(lambda x: get_NOx_subindex(x))
city_hour['NH3_SubIndex'] = city_hour['NH3'].apply(lambda x: get_NH3_subindex(x))
city_hour['CO_SubIndex'] = city_hour['CO'].apply(lambda x: get_CO_subindex(x))
city_hour['O3_SubIndex'] = city_hour['O3'].apply(lambda x: get_O3_subindex(x))

# --- STEP 3: Get the Max AQI ---
city_hour['Calculated_AQI'] = city_hour[[
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex'
]].max(axis=1)

# --- STEP 4: Fill the Missing AQI Values ---
# We fill NaNs in the original 'AQI' column with our calculated values
city_hour['AQI'] = city_hour['AQI'].fillna(city_hour['Calculated_AQI'])
city_hour['AQI_Bucket'] = city_hour['AQI'].apply(get_aqi_bucket)

# --- Clean Up ---
# Drop the helper columns to keep it clean
cols_to_drop = [
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex', 
    'Calculated_AQI'
]
city_hour.drop(columns=cols_to_drop, inplace=True, errors='ignore')

print("city_hour AQI calculated successfully!")
print("Remaining Missing AQI:", city_hour['AQI'].isnull().sum())
print(city_hour[['City', 'Datetime', 'AQI', 'AQI_Bucket']].head())

Calculating sub-indices...
city_hour AQI calculated successfully!
Remaining Missing AQI: 0
        City            Datetime         AQI AQI_Bucket
0  Ahmedabad 2015-01-01 01:00:00  178.794118   Moderate
1  Ahmedabad 2015-01-01 02:00:00  178.794118   Moderate
2  Ahmedabad 2015-01-01 03:00:00  178.794118   Moderate
3  Ahmedabad 2015-01-01 04:00:00  178.794118   Moderate
4  Ahmedabad 2015-01-01 05:00:00  113.373333   Moderate

In [53]:
city_hour.isnull().sum()

City               0
Datetime           0
PM2.5              0
PM10               0
NO            116632
NO2                0
NOx           123224
NH3                0
CO                 0
SO2                0
O3                 0
Benzene       163646
Toluene       220607
Xylene        455829
AQI                0
AQI_Bucket         0
Date               0
Time               0
dtype: int64

In [55]:
city_hour.head(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Date,Time
0,Ahmedabad,2015-01-01 01:00:00,36.6,120.06,1.00,40.01,36.37,19.88,1.00,122.07,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,01:00:00
1,Ahmedabad,2015-01-01 02:00:00,36.6,120.06,0.02,27.75,19.73,19.88,0.02,85.90,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,02:00:00
2,Ahmedabad,2015-01-01 03:00:00,36.6,120.06,0.08,19.32,11.08,19.88,0.08,52.83,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,03:00:00
3,Ahmedabad,2015-01-01 04:00:00,36.6,120.06,0.30,16.45,9.20,19.88,0.30,39.53,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,04:00:00
4,Ahmedabad,2015-01-01 05:00:00,36.6,120.06,0.12,14.90,7.85,19.88,0.12,32.63,108.915000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,05:00:00
5,Ahmedabad,2015-01-01 06:00:00,36.6,120.06,0.33,15.95,10.82,19.88,0.33,29.87,64.250000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,06:00:00
6,Ahmedabad,2015-01-01 07:00:00,36.6,120.06,0.45,15.94,12.47,19.88,0.45,27.41,191.960000,0.0,0.00,0.0,259.900000,Poor,2015-01-01,07:00:00
7,Ahmedabad,2015-01-01 08:00:00,36.6,120.06,1.03,16.66,16.48,19.88,1.03,20.92,177.210000,0.0,0.00,0.0,223.025000,Poor,2015-01-01,08:00:00
8,Ahmedabad,2015-01-01 09:00:00,36.6,120.06,1.47,16.25,18.02,19.88,1.47,16.45,122.080000,0.0,0.00,0.0,132.470588,Moderate,2015-01-01,09:00:00
9,Ahmedabad,2015-01-01 10:00:00,36.6,120.06,2.05,13.78,16.08,19.88,2.05,15.14,110.625000,0.0,0.00,0.0,115.625000,Moderate,2015-01-01,10:00:00
10,Ahmedabad,2015-01-01 11:00:00,36.6,120.06,2.27,13.87,16.73,19.88,2.27,14.12,99.170000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,11:00:00
11,Ahmedabad,2015-01-01 12:00:00,36.6,120.06,1.73,12.87,14.63,19.88,1.73,13.26,91.670000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,12:00:00
12,Ahmedabad,2015-01-01 13:00:00,36.6,120.06,1.72,14.15,15.55,19.88,1.72,17.20,95.920000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,13:00:00
13,Ahmedabad,2015-01-01 14:00:00,36.6,120.06,1.85,15.74,17.62,19.88,1.85,18.78,118.845000,0.0,0.00,0.0,127.713235,Moderate,2015-01-01,14:00:00
14,Ahmedabad,2015-01-01 15:00:00,36.6,120.06,0.95,15.94,16.18,19.88,0.95,19.16,141.770000,0.0,0.00,0.0,161.426471,Moderate,2015-01-01,15:00:00
15,Ahmedabad,2015-01-01 16:00:00,36.6,120.06,0.87,17.28,18.32,19.88,0.87,17.83,164.695000,0.0,0.00,0.0,195.139706,Moderate,2015-01-01,16:00:00
16,Ahmedabad,2015-01-01 17:00:00,36.6,120.06,0.80,19.04,20.00,19.88,0.80,16.14,187.620000,0.0,0.00,0.0,249.050000,Poor,2015-01-01,17:00:00
17,Ahmedabad,2015-01-01 18:00:00,36.6,120.06,0.47,21.24,22.70,19.88,0.47,11.93,187.553333,0.0,0.00,0.0,248.883333,Poor,2015-01-01,18:00:00
18,Ahmedabad,2015-01-01 19:00:00,36.6,120.06,0.53,25.63,27.42,19.88,0.53,14.99,187.486667,0.0,0.33,0.0,248.716667,Poor,2015-01-01,19:00:00
19,Ahmedabad,2015-01-01 20:00:00,36.6,120.06,0.47,16.22,16.00,19.88,0.47,13.66,187.420000,0.0,0.23,0.0,248.550000,Poor,2015-01-01,20:00:00

In [56]:
city_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707875 entries, 0 to 707874
Data columns (total 18 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   City        707875 non-null  object
 1   Datetime    707875 non-null  datetime64[ns]
 2   PM2.5       707875 non-null  float64
 3   PM10        707875 non-null  float64
 4   NO          591243 non-null  float64
 5   NO2         707875 non-null  float64
 6   NOx         584651 non-null  float64
 7   NH3         707875 non-null  float64
 8   CO          707875 non-null  float64
 9   SO2         707875 non-null  float64
 10  O3          707875 non-null  float64
 11  Benzene     544229 non-null  float64
 12  Toluene     487268 non-null  float64
 13  Xylene      252046 non-null  float64
 14  AQI         707875 non-null  float64
 15  AQI_Bucket  707875 non-null  object
 16  Date        707875 non-null  object
 17  Time        707875 non-null  object
dtypes: datetime64[ns](1), float64(13), object(4)
memory usage: 97.2+ MB

In [57]:
station_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108035 entries, 0 to 108034
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   StationId   108035 non-null  object
 1   Date        108035 non-null  object
 2   PM2.5       86410 non-null   float64
 3   PM10        65329 non-null   float64
 4   NO          90929 non-null   float64
 5   NO2         91488 non-null   float64
 6   NOx         92535 non-null   float64
 7   NH3         59930 non-null   float64
 8   CO          95037 non-null   float64
 9   SO2         82831 non-null   float64
 10  O3          82467 non-null   float64
 11  Benzene     76580 non-null   float64
 12  Toluene     69333 non-null   float64
 13  Xylene      22898 non-null   float64
 14  AQI         87025 non-null   float64
 15  AQI_Bucket  87025 non-null   object
dtypes: float64(13), object(3)
memory usage: 13.2+ MB

In [59]:
station_day.head(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,AP001,2017-11-24,71.36,115.75,1.75,20.65,12.40,12.19,0.10,10.76,109.26,0.17,5.92,0.10,NaN,NaN
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0,Moderate
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0,Moderate
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0,Moderate
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0,Moderate
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0,Moderate
6,AP001,2017-11-30,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,165.0,Moderate
7,AP001,2017-12-01,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,191.0,Moderate
8,AP001,2017-12-02,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,191.0,Moderate
9,AP001,2017-12-03,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,227.0,Poor
10,AP001,2017-12-04,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,168.0,Moderate
11,AP001,2017-12-05,88.36,121.77,3.70,20.23,13.75,13.72,0.12,14.02,117.93,0.24,2.92,0.03,198.0,Moderate
12,AP001,2017-12-06,96.83,139.36,1.60,25.65,14.99,15.12,0.11,16.54,117.21,0.29,4.45,0.07,201.0,Poor
13,AP001,2017-12-07,117.46,181.64,4.26,41.10,25.32,17.34,0.13,28.79,94.63,0.36,6.21,0.17,252.0,Poor
14,AP001,2017-12-08,122.88,208.86,5.56,54.87,33.71,17.96,0.27,22.97,68.60,0.36,6.28,0.21,310.0,Very Poor
15,AP001,2017-12-09,74.28,141.22,6.10,44.97,28.88,15.73,0.09,21.90,60.62,0.26,4.79,0.16,196.0,Moderate
16,AP001,2017-12-10,50.32,102.77,1.73,33.85,19.41,12.56,0.10,13.65,68.15,0.20,4.29,0.10,132.0,Moderate
17,AP001,2017-12-11,58.47,115.27,4.93,41.64,26.15,15.20,0.16,18.37,73.75,0.23,5.51,0.16,147.0,Moderate
18,AP001,2017-12-12,89.35,131.48,7.97,42.10,28.88,21.24,0.24,7.42,44.67,0.28,7.01,0.19,179.0,Moderate
19,AP001,2017-12-13,64.42,99.74,7.20,34.78,24.36,17.63,0.15,5.81,50.16,0.24,6.11,0.14,145.0,Moderate

In [61]:
station_day.isnull().sum()

StationId         0
Date              0
PM2.5         21625
PM10          42706
NO            17106
NO2           16547
NOx           15500
NH3           48105
CO            12998
SO2           25204
O3            25568
Benzene       31455
Toluene       38702
Xylene        85137
AQI           21010
AQI_Bucket    21010
dtype: int64

In [62]:
import pandas as pd
import numpy as np

# --- STEP 1: Define the Calculation Formulas (Recipes) ---
# (Same formulas as before, re-defined here to be safe)

def get_PM25_subindex(x):
    if pd.isnull(x): return 0
    if x <= 30: return x * 50 / 30
    elif x <= 60: return 50 + (x - 30) * 50 / 30
    elif x <= 90: return 100 + (x - 60) * 100 / 30
    elif x <= 120: return 200 + (x - 90) * 100 / 30
    elif x <= 250: return 300 + (x - 120) * 100 / 130
    elif x > 250: return 400 + (x - 250) * 100 / 130
    else: return 0

def get_PM10_subindex(x):
    if pd.isnull(x): return 0
    if x <= 50: return x
    elif x <= 100: return x
    elif x <= 250: return 100 + (x - 100) * 100 / 150
    elif x <= 350: return 200 + (x - 250) * 100 / 100
    elif x <= 430: return 300 + (x - 350) * 100 / 80
    elif x > 430: return 400 + (x - 430) * 100 / 80
    else: return 0

def get_SO2_subindex(x):
    if pd.isnull(x): return 0
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 380: return 100 + (x - 80) * 100 / 300
    elif x <= 800: return 200 + (x - 380) * 100 / 420
    elif x <= 1600: return 300 + (x - 800) * 100 / 800
    elif x > 1600: return 400 + (x - 1600) * 100 / 800
    else: return 0

def get_NOx_subindex(x):
    if pd.isnull(x): return 0
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 180: return 100 + (x - 80) * 100 / 100
    elif x <= 280: return 200 + (x - 180) * 100 / 100
    elif x <= 400: return 300 + (x - 280) * 100 / 120
    elif x > 400: return 400 + (x - 400) * 100 / 120
    else: return 0

def get_NH3_subindex(x):
    if pd.isnull(x): return 0
    if x <= 200: return x * 50 / 200
    elif x <= 400: return 50 + (x - 200) * 50 / 200
    elif x <= 800: return 100 + (x - 400) * 100 / 400
    elif x <= 1200: return 200 + (x - 800) * 100 / 400
    elif x <= 1800: return 300 + (x - 1200) * 100 / 600
    elif x > 1800: return 400 + (x - 1800) * 100 / 600
    else: return 0

def get_CO_subindex(x):
    if pd.isnull(x): return 0
    if x <= 1: return x * 50 / 1
    elif x <= 2: return 50 + (x - 1) * 50 / 1
    elif x <= 10: return 100 + (x - 2) * 100 / 8
    elif x <= 17: return 200 + (x - 10) * 100 / 7
    elif x <= 34: return 300 + (x - 17) * 100 / 17
    elif x > 34: return 400 + (x - 34) * 100 / 17
    else: return 0

def get_O3_subindex(x):
    if pd.isnull(x): return 0
    if x <= 50: return x * 50 / 50
    elif x <= 100: return 50 + (x - 50) * 50 / 50
    elif x <= 168: return 100 + (x - 100) * 100 / 68
    elif x <= 208: return 200 + (x - 168) * 100 / 40
    elif x <= 748: return 300 + (x - 208) * 100 / 539
    elif x > 748: return 400 + (x - 748) * 100 / 539
    else: return 0

def get_aqi_bucket(x):
    if pd.isnull(x): return 'Unknown'
    if x <= 50: return 'Good'
    elif x <= 100: return 'Satisfactory'
    elif x <= 200: return 'Moderate'
    elif x <= 300: return 'Poor'
    elif x <= 400: return 'Very Poor'
    else: return 'Severe'


# --- STEP 2: Prep the Pollutant Data (Interpolate first) ---
# We fill the missing pollutant values first, so the formula has numbers to work with.
# Grouping by StationId ensures we don't mix data between stations.

station_day['Date'] = pd.to_datetime(station_day['Date'])
pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3']

for col in pollutants:
    station_day[col] = station_day.groupby('StationId')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )

# --- STEP 3: Calculate Sub-Indices ---
print("Calculating sub-indices for station_day...")
station_day['PM2.5_SubIndex'] = station_day['PM2.5'].apply(lambda x: get_PM25_subindex(x))
station_day['PM10_SubIndex'] = station_day['PM10'].apply(lambda x: get_PM10_subindex(x))
station_day['SO2_SubIndex'] = station_day['SO2'].apply(lambda x: get_SO2_subindex(x))
station_day['NOx_SubIndex'] = station_day['NOx'].apply(lambda x: get_NOx_subindex(x))
station_day['NH3_SubIndex'] = station_day['NH3'].apply(lambda x: get_NH3_subindex(x))
station_day['CO_SubIndex'] = station_day['CO'].apply(lambda x: get_CO_subindex(x))
station_day['O3_SubIndex'] = station_day['O3'].apply(lambda x: get_O3_subindex(x))

# --- STEP 4: Calculate Final AQI (The Max) ---
station_day['Calculated_AQI'] = station_day[[
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex'
]].max(axis=1)

# --- STEP 5: Overwrite the AQI Column ---
station_day['AQI'] = station_day['AQI'].fillna(station_day['Calculated_AQI'])
station_day['AQI_Bucket'] = station_day['AQI'].apply(get_aqi_bucket)

# --- Clean Up ---
cols_to_drop = [
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex', 
    'Calculated_AQI'
]
station_day.drop(columns=cols_to_drop, inplace=True, errors='ignore')

print("station_day AQI Calculated Successfully!")
print("Remaining Missing AQI:", station_day['AQI'].isnull().sum())

Calculating sub-indices for station_day...
station_day AQI Calculated Successfully!
Remaining Missing AQI: 0

In [64]:
station_day.head(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,AP001,2017-11-24,71.36,115.75,1.75,20.65,12.40,12.19,0.10,10.76,109.26,0.17,5.92,0.10,137.866667,Moderate
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.000000,Moderate
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.000000,Moderate
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.000000,Moderate
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.000000,Moderate
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.000000,Moderate
6,AP001,2017-11-30,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,165.000000,Moderate
7,AP001,2017-12-01,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,191.000000,Moderate
8,AP001,2017-12-02,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,191.000000,Moderate
9,AP001,2017-12-03,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,227.000000,Poor
10,AP001,2017-12-04,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,168.000000,Moderate
11,AP001,2017-12-05,88.36,121.77,3.70,20.23,13.75,13.72,0.12,14.02,117.93,0.24,2.92,0.03,198.000000,Moderate
12,AP001,2017-12-06,96.83,139.36,1.60,25.65,14.99,15.12,0.11,16.54,117.21,0.29,4.45,0.07,201.000000,Poor
13,AP001,2017-12-07,117.46,181.64,4.26,41.10,25.32,17.34,0.13,28.79,94.63,0.36,6.21,0.17,252.000000,Poor
14,AP001,2017-12-08,122.88,208.86,5.56,54.87,33.71,17.96,0.27,22.97,68.60,0.36,6.28,0.21,310.000000,Very Poor
15,AP001,2017-12-09,74.28,141.22,6.10,44.97,28.88,15.73,0.09,21.90,60.62,0.26,4.79,0.16,196.000000,Moderate
16,AP001,2017-12-10,50.32,102.77,1.73,33.85,19.41,12.56,0.10,13.65,68.15,0.20,4.29,0.10,132.000000,Moderate
17,AP001,2017-12-11,58.47,115.27,4.93,41.64,26.15,15.20,0.16,18.37,73.75,0.23,5.51,0.16,147.000000,Moderate
18,AP001,2017-12-12,89.35,131.48,7.97,42.10,28.88,21.24,0.24,7.42,44.67,0.28,7.01,0.19,179.000000,Moderate
19,AP001,2017-12-13,64.42,99.74,7.20,34.78,24.36,17.63,0.15,5.81,50.16,0.24,6.11,0.14,145.000000,Moderate

In [65]:
station_day.tail(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
108015,WB013,2020-06-12,8.12,15.45,2.850000,22.520000,25.36,24.180000,0.71,1.71,19.12,6.80,13.68,NaN,41.0,Good
108016,WB013,2020-06-13,12.48,23.05,2.770000,19.600000,22.36,23.540000,0.71,1.55,19.59,4.15,10.72,NaN,41.0,Good
108017,WB013,2020-06-14,11.52,20.89,2.360000,16.860000,19.22,23.210000,0.71,1.12,20.23,1.71,8.11,NaN,42.0,Good
108018,WB013,2020-06-15,13.50,26.43,2.630000,22.980000,25.60,25.300000,0.75,1.54,21.79,2.13,8.67,NaN,41.0,Good
108019,WB013,2020-06-16,14.06,23.73,2.770000,23.800000,26.57,24.020000,0.71,1.68,20.59,2.07,8.70,NaN,38.0,Good
108020,WB013,2020-06-17,16.49,33.70,3.030000,24.640000,27.64,28.080000,0.70,2.03,19.30,2.20,9.23,NaN,40.0,Good
108021,WB013,2020-06-18,16.47,36.74,2.860000,24.450000,27.31,27.570000,0.70,3.54,22.69,1.94,9.02,NaN,42.0,Good
108022,WB013,2020-06-19,18.62,41.66,3.380000,25.960000,29.34,27.720000,0.72,2.73,23.09,2.42,8.81,NaN,42.0,Good
108023,WB013,2020-06-20,11.22,28.40,2.930000,15.690000,18.62,32.750000,0.72,1.14,19.87,1.34,8.34,NaN,40.0,Good
108024,WB013,2020-06-21,11.24,22.40,2.130000,14.140000,16.31,29.420000,0.64,1.43,24.31,2.19,8.80,NaN,38.0,Good
108025,WB013,2020-06-22,15.10,30.98,2.590000,18.040000,20.63,30.340000,0.67,1.50,25.84,1.28,8.32,NaN,38.0,Good
108026,WB013,2020-06-23,19.48,42.37,3.060000,20.940000,23.99,32.530000,0.70,1.72,28.21,1.65,5.93,NaN,44.0,Good
108027,WB013,2020-06-24,20.05,46.63,3.780000,15.280000,19.06,18.890000,0.66,7.08,41.56,1.14,7.24,NaN,59.0,Satisfactory
108028,WB013,2020-06-25,17.03,39.64,3.230000,11.420000,14.65,18.980000,0.57,11.39,31.76,0.79,6.85,NaN,56.0,Satisfactory
108029,WB013,2020-06-26,9.79,19.87,23.510000,16.500000,40.02,25.090000,0.66,10.34,30.19,0.93,6.37,NaN,50.0,Good
108030,WB013,2020-06-27,8.65,16.46,20.223333,77.956667,98.08,20.526667,0.69,4.36,30.59,1.32,7.26,NaN,50.0,Good
108031,WB013,2020-06-28,11.80,18.47,16.936667,139.413333,156.14,15.963333,0.68,3.49,38.95,1.42,7.92,NaN,65.0,Satisfactory
108032,WB013,2020-06-29,18.60,32.26,13.650000,200.870000,214.20,11.400000,0.78,5.12,38.17,3.52,8.64,NaN,63.0,Satisfactory
108033,WB013,2020-06-30,16.07,39.30,7.560000,29.130000,36.69,29.260000,0.69,5.88,29.64,1.86,8.40,NaN,57.0,Satisfactory
108034,WB013,2020-07-01,10.50,36.50,7.780000,22.500000,30.25,27.230000,0.58,2.80,13.10,1.31,7.39,NaN,59.0,Satisfactory

In [66]:
station_day.isnull().sum()

StationId         0
Date              0
PM2.5          4948
PM10          30172
NO              738
NO2               0
NOx            3460
NH3           39604
CO             1553
SO2            9128
O3            10594
Benzene       31455
Toluene       38702
Xylene        85137
AQI               0
AQI_Bucket        0
dtype: int64

ignore above station_day ones

In [67]:
import pandas as pd
import numpy as np

print("--- STARTING FRESH REPAIR ---")

# 1. LOAD THE DATA FROM SCRATCH (Wipes out all previous mistakes)
# (Make sure the filenames match what you have on your system)
station_day = pd.read_csv('station_day.csv')
stations = pd.read_csv('stations.csv')

# 2. MERGE CITY INFO (We need this to know which city a station belongs to)
station_day['Date'] = pd.to_datetime(station_day['Date'])
station_day = station_day.merge(stations[['StationId', 'City']], on='StationId', how='left')

# 3. DEFINE THE FORMULAS (The Recipes)
def get_PM25_subindex(x):
    if x <= 30: return x * 50 / 30
    elif x <= 60: return 50 + (x - 30) * 50 / 30
    elif x <= 90: return 100 + (x - 60) * 100 / 30
    elif x <= 120: return 200 + (x - 90) * 100 / 30
    elif x <= 250: return 300 + (x - 120) * 100 / 130
    elif x > 250: return 400 + (x - 250) * 100 / 130
    else: return 0

def get_PM10_subindex(x):
    if x <= 50: return x
    elif x <= 100: return x
    elif x <= 250: return 100 + (x - 100) * 100 / 150
    elif x <= 350: return 200 + (x - 250) * 100 / 100
    elif x <= 430: return 300 + (x - 350) * 100 / 80
    elif x > 430: return 400 + (x - 430) * 100 / 80
    else: return 0

def get_SO2_subindex(x):
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 380: return 100 + (x - 80) * 100 / 300
    elif x <= 800: return 200 + (x - 380) * 100 / 420
    elif x <= 1600: return 300 + (x - 800) * 100 / 800
    elif x > 1600: return 400 + (x - 1600) * 100 / 800
    else: return 0

def get_NOx_subindex(x):
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 180: return 100 + (x - 80) * 100 / 100
    elif x <= 280: return 200 + (x - 180) * 100 / 100
    elif x <= 400: return 300 + (x - 280) * 100 / 120
    elif x > 400: return 400 + (x - 400) * 100 / 120
    else: return 0

def get_NH3_subindex(x):
    if x <= 200: return x * 50 / 200
    elif x <= 400: return 50 + (x - 200) * 50 / 200
    elif x <= 800: return 100 + (x - 400) * 100 / 400
    elif x <= 1200: return 200 + (x - 800) * 100 / 400
    elif x <= 1800: return 300 + (x - 1200) * 100 / 600
    elif x > 1800: return 400 + (x - 1800) * 100 / 600
    else: return 0

def get_CO_subindex(x):
    if x <= 1: return x * 50 / 1
    elif x <= 2: return 50 + (x - 1) * 50 / 1
    elif x <= 10: return 100 + (x - 2) * 100 / 8
    elif x <= 17: return 200 + (x - 10) * 100 / 7
    elif x <= 34: return 300 + (x - 17) * 100 / 17
    elif x > 34: return 400 + (x - 34) * 100 / 17
    else: return 0

def get_O3_subindex(x):
    if x <= 50: return x * 50 / 50
    elif x <= 100: return 50 + (x - 50) * 50 / 50
    elif x <= 168: return 100 + (x - 100) * 100 / 68
    elif x <= 208: return 200 + (x - 168) * 100 / 40
    elif x <= 748: return 300 + (x - 208) * 100 / 539
    elif x > 748: return 400 + (x - 748) * 100 / 539
    else: return 0

def get_aqi_bucket(x):
    if pd.isnull(x): return 'Unknown'
    if x <= 50: return 'Good'
    elif x <= 100: return 'Satisfactory'
    elif x <= 200: return 'Moderate'
    elif x <= 300: return 'Poor'
    elif x <= 400: return 'Very Poor'
    else: return 'Severe'

# 4. THE CLEANUP (The Smart Strategy)
pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3']

print("1. Filling missing pollutant data...")
# A. First, try to fill using the same station (interpolation)
# This is good for small gaps (missing 1 day)
for col in pollutants:
    station_day[col] = station_day.groupby('StationId')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )

# B. Second, for big gaps (empty station), fill using the CITY Average for that day
for col in pollutants:
    station_day[col] = station_day[col].fillna(
        station_day.groupby(['City', 'Date'])[col].transform('median')
    )

# C. Third, fallback to Country Average if City is also empty
for col in pollutants:
    station_day[col] = station_day[col].fillna(
        station_day.groupby('Date')[col].transform('median')
    )

# D. Final safety net (Forward/Back fill)
station_day[pollutants] = station_day[pollutants].ffill().bfill()

--- STARTING FRESH REPAIR ---
1. Filling missing pollutant data...

In [68]:
station_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108035 entries, 0 to 108034
Data columns (total 17 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   StationId   108035 non-null  object
 1   Date        108035 non-null  datetime64[ns]
 2   PM2.5       108035 non-null  float64
 3   PM10        108035 non-null  float64
 4   NO          108035 non-null  float64
 5   NO2         108035 non-null  float64
 6   NOx         108035 non-null  float64
 7   NH3         108035 non-null  float64
 8   CO          108035 non-null  float64
 9   SO2         108035 non-null  float64
 10  O3          108035 non-null  float64
 11  Benzene     76580 non-null   float64
 12  Toluene     69333 non-null   float64
 13  Xylene      22898 non-null   float64
 14  AQI         87025 non-null   float64
 15  AQI_Bucket  87025 non-null   object
 16  City        108035 non-null  object
dtypes: datetime64[ns](1), float64(13), object(3)
memory usage: 14.0+ MB

In [69]:
station_day.head(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
0,AP001,2017-11-24,71.36,115.75,1.75,20.65,12.40,12.19,0.10,10.76,109.26,0.17,5.92,0.10,NaN,NaN,Amaravati
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,184.0,Moderate,Amaravati
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,197.0,Moderate,Amaravati
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,198.0,Moderate,Amaravati
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,188.0,Moderate,Amaravati
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,173.0,Moderate,Amaravati
6,AP001,2017-11-30,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,165.0,Moderate,Amaravati
7,AP001,2017-12-01,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,191.0,Moderate,Amaravati
8,AP001,2017-12-02,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,191.0,Moderate,Amaravati
9,AP001,2017-12-03,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,227.0,Poor,Amaravati
10,AP001,2017-12-04,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,168.0,Moderate,Amaravati
11,AP001,2017-12-05,88.36,121.77,3.70,20.23,13.75,13.72,0.12,14.02,117.93,0.24,2.92,0.03,198.0,Moderate,Amaravati
12,AP001,2017-12-06,96.83,139.36,1.60,25.65,14.99,15.12,0.11,16.54,117.21,0.29,4.45,0.07,201.0,Poor,Amaravati
13,AP001,2017-12-07,117.46,181.64,4.26,41.10,25.32,17.34,0.13,28.79,94.63,0.36,6.21,0.17,252.0,Poor,Amaravati
14,AP001,2017-12-08,122.88,208.86,5.56,54.87,33.71,17.96,0.27,22.97,68.60,0.36,6.28,0.21,310.0,Very Poor,Amaravati
15,AP001,2017-12-09,74.28,141.22,6.10,44.97,28.88,15.73,0.09,21.90,60.62,0.26,4.79,0.16,196.0,Moderate,Amaravati
16,AP001,2017-12-10,50.32,102.77,1.73,33.85,19.41,12.56,0.10,13.65,68.15,0.20,4.29,0.10,132.0,Moderate,Amaravati
17,AP001,2017-12-11,58.47,115.27,4.93,41.64,26.15,15.20,0.16,18.37,73.75,0.23,5.51,0.16,147.0,Moderate,Amaravati
18,AP001,2017-12-12,89.35,131.48,7.97,42.10,28.88,21.24,0.24,7.42,44.67,0.28,7.01,0.19,179.0,Moderate,Amaravati
19,AP001,2017-12-13,64.42,99.74,7.20,34.78,24.36,17.63,0.15,5.81,50.16,0.24,6.11,0.14,145.0,Moderate,Amaravati

In [70]:
station_day.isnull().sum()

StationId         0
Date              0
PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
CO                0
SO2               0
O3                0
Benzene       31455
Toluene       38702
Xylene        85137
AQI           21010
AQI_Bucket    21010
City              0
dtype: int64

In [71]:
# 5. CALCULATE AQI (Fresh Calculation on Clean Data)
print("2. Calculating AQI from scratch...")
station_day['PM2.5_SubIndex'] = station_day['PM2.5'].apply(lambda x: get_PM25_subindex(x))
station_day['PM10_SubIndex'] = station_day['PM10'].apply(lambda x: get_PM10_subindex(x))
station_day['SO2_SubIndex'] = station_day['SO2'].apply(lambda x: get_SO2_subindex(x))
station_day['NOx_SubIndex'] = station_day['NOx'].apply(lambda x: get_NOx_subindex(x))
station_day['NH3_SubIndex'] = station_day['NH3'].apply(lambda x: get_NH3_subindex(x))
station_day['CO_SubIndex'] = station_day['CO'].apply(lambda x: get_CO_subindex(x))
station_day['O3_SubIndex'] = station_day['O3'].apply(lambda x: get_O3_subindex(x))

station_day['Calculated_AQI'] = station_day[[
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex'
]].max(axis=1)

# Overwrite the old AQI column completely
station_day['AQI'] = station_day['Calculated_AQI']
station_day['AQI_Bucket'] = station_day['AQI'].apply(get_aqi_bucket)

# 6. DROP TEMP COLUMNS
cols_to_drop = [
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex', 
    'Calculated_AQI'
]
station_day.drop(columns=cols_to_drop, inplace=True, errors='ignore')

print("--- SUCCESS ---")
print("Remaining Missing Values:")
print(station_day[['PM2.5', 'AQI']].isnull().sum())
print("\nFirst 5 rows of Clean Data:")
print(station_day[['StationId', 'City', 'Date', 'AQI', 'AQI_Bucket']].head())

2. Calculating AQI from scratch...
--- SUCCESS ---
Remaining Missing Values:
PM2.5    0
AQI      0
dtype: int64

First 5 rows of Clean Data:
  StationId       City       Date         AQI AQI_Bucket
0     AP001  Amaravati 2017-11-24  137.866667   Moderate
1     AP001  Amaravati 2017-11-25  171.333333   Moderate
2     AP001  Amaravati 2017-11-26  161.066667   Moderate
3     AP001  Amaravati 2017-11-27  195.866667   Moderate
4     AP001  Amaravati 2017-11-28  156.147059   Moderate

In [72]:
station_day.isnull().sum()

StationId         0
Date              0
PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
CO                0
SO2               0
O3                0
Benzene       31455
Toluene       38702
Xylene        85137
AQI               0
AQI_Bucket        0
City              0
dtype: int64

In [73]:
station_day.head(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
0,AP001,2017-11-24,71.36,115.75,1.75,20.65,12.40,12.19,0.10,10.76,109.26,0.17,5.92,0.10,137.866667,Moderate,Amaravati
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,171.333333,Moderate,Amaravati
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,161.066667,Moderate,Amaravati
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,195.866667,Moderate,Amaravati
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,156.147059,Moderate,Amaravati
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,141.566667,Moderate,Amaravati
6,AP001,2017-11-30,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,132.666667,Moderate,Amaravati
7,AP001,2017-12-01,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,146.533333,Moderate,Amaravati
8,AP001,2017-12-02,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,199.666667,Moderate,Amaravati
9,AP001,2017-12-03,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,190.466667,Moderate,Amaravati
10,AP001,2017-12-04,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,182.133333,Moderate,Amaravati
11,AP001,2017-12-05,88.36,121.77,3.70,20.23,13.75,13.72,0.12,14.02,117.93,0.24,2.92,0.03,194.533333,Moderate,Amaravati
12,AP001,2017-12-06,96.83,139.36,1.60,25.65,14.99,15.12,0.11,16.54,117.21,0.29,4.45,0.07,222.766667,Poor,Amaravati
13,AP001,2017-12-07,117.46,181.64,4.26,41.10,25.32,17.34,0.13,28.79,94.63,0.36,6.21,0.17,291.533333,Poor,Amaravati
14,AP001,2017-12-08,122.88,208.86,5.56,54.87,33.71,17.96,0.27,22.97,68.60,0.36,6.28,0.21,302.215385,Very Poor,Amaravati
15,AP001,2017-12-09,74.28,141.22,6.10,44.97,28.88,15.73,0.09,21.90,60.62,0.26,4.79,0.16,147.600000,Moderate,Amaravati
16,AP001,2017-12-10,50.32,102.77,1.73,33.85,19.41,12.56,0.10,13.65,68.15,0.20,4.29,0.10,101.846667,Moderate,Amaravati
17,AP001,2017-12-11,58.47,115.27,4.93,41.64,26.15,15.20,0.16,18.37,73.75,0.23,5.51,0.16,110.180000,Moderate,Amaravati
18,AP001,2017-12-12,89.35,131.48,7.97,42.10,28.88,21.24,0.24,7.42,44.67,0.28,7.01,0.19,197.833333,Moderate,Amaravati
19,AP001,2017-12-13,64.42,99.74,7.20,34.78,24.36,17.63,0.15,5.81,50.16,0.24,6.11,0.14,114.733333,Moderate,Amaravati

In [74]:
station_day.tail(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
108015,WB013,2020-06-12,8.12,15.45,2.850000,22.520000,25.36,24.180000,0.71,1.71,19.12,6.80,13.68,NaN,35.5000,Good,Kolkata
108016,WB013,2020-06-13,12.48,23.05,2.770000,19.600000,22.36,23.540000,0.71,1.55,19.59,4.15,10.72,NaN,35.5000,Good,Kolkata
108017,WB013,2020-06-14,11.52,20.89,2.360000,16.860000,19.22,23.210000,0.71,1.12,20.23,1.71,8.11,NaN,35.5000,Good,Kolkata
108018,WB013,2020-06-15,13.50,26.43,2.630000,22.980000,25.60,25.300000,0.75,1.54,21.79,2.13,8.67,NaN,37.5000,Good,Kolkata
108019,WB013,2020-06-16,14.06,23.73,2.770000,23.800000,26.57,24.020000,0.71,1.68,20.59,2.07,8.70,NaN,35.5000,Good,Kolkata
108020,WB013,2020-06-17,16.49,33.70,3.030000,24.640000,27.64,28.080000,0.70,2.03,19.30,2.20,9.23,NaN,35.0000,Good,Kolkata
108021,WB013,2020-06-18,16.47,36.74,2.860000,24.450000,27.31,27.570000,0.70,3.54,22.69,1.94,9.02,NaN,36.7400,Good,Kolkata
108022,WB013,2020-06-19,18.62,41.66,3.380000,25.960000,29.34,27.720000,0.72,2.73,23.09,2.42,8.81,NaN,41.6600,Good,Kolkata
108023,WB013,2020-06-20,11.22,28.40,2.930000,15.690000,18.62,32.750000,0.72,1.14,19.87,1.34,8.34,NaN,36.0000,Good,Kolkata
108024,WB013,2020-06-21,11.24,22.40,2.130000,14.140000,16.31,29.420000,0.64,1.43,24.31,2.19,8.80,NaN,32.0000,Good,Kolkata
108025,WB013,2020-06-22,15.10,30.98,2.590000,18.040000,20.63,30.340000,0.67,1.50,25.84,1.28,8.32,NaN,33.5000,Good,Kolkata
108026,WB013,2020-06-23,19.48,42.37,3.060000,20.940000,23.99,32.530000,0.70,1.72,28.21,1.65,5.93,NaN,42.3700,Good,Kolkata
108027,WB013,2020-06-24,20.05,46.63,3.780000,15.280000,19.06,18.890000,0.66,7.08,41.56,1.14,7.24,NaN,46.6300,Good,Kolkata
108028,WB013,2020-06-25,17.03,39.64,3.230000,11.420000,14.65,18.980000,0.57,11.39,31.76,0.79,6.85,NaN,39.6400,Good,Kolkata
108029,WB013,2020-06-26,9.79,19.87,23.510000,16.500000,40.02,25.090000,0.66,10.34,30.19,0.93,6.37,NaN,50.0250,Satisfactory,Kolkata
108030,WB013,2020-06-27,8.65,16.46,20.223333,77.956667,98.08,20.526667,0.69,4.36,30.59,1.32,7.26,NaN,118.0800,Moderate,Kolkata
108031,WB013,2020-06-28,11.80,18.47,16.936667,139.413333,156.14,15.963333,0.68,3.49,38.95,1.42,7.92,NaN,176.1400,Moderate,Kolkata
108032,WB013,2020-06-29,18.60,32.26,13.650000,200.870000,214.20,11.400000,0.78,5.12,38.17,3.52,8.64,NaN,234.2000,Poor,Kolkata
108033,WB013,2020-06-30,16.07,39.30,7.560000,29.130000,36.69,29.260000,0.69,5.88,29.64,1.86,8.40,NaN,45.8625,Good,Kolkata
108034,WB013,2020-07-01,10.50,36.50,7.780000,22.500000,30.25,27.230000,0.58,2.80,13.10,1.31,7.39,NaN,37.8125,Good,Kolkata

In [75]:
station_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589083 entries, 0 to 2589082
Data columns (total 16 columns):
 #   Column      Dtype
---  ------      -----
 0   StationId   object
 1   Datetime    object
 2   PM2.5       float64
 3   PM10        float64
 4   NO          float64
 5   NO2         float64
 6   NOx         float64
 7   NH3         float64
 8   CO          float64
 9   SO2         float64
 10  O3          float64
 11  Benzene     float64
 12  Toluene     float64
 13  Xylene      float64
 14  AQI         float64
 15  AQI_Bucket  object
dtypes: float64(13), object(3)
memory usage: 316.1+ MB

In [76]:
station_hour.isnull().sum()

StationId           0
Datetime            0
PM2.5          647689
PM10          1119252
NO             553711
NO2            528973
NOx            490808
NH3           1236618
CO             499302
SO2            742737
O3             725973
Benzene        861579
Toluene       1042366
Xylene        2075104
AQI            570190
AQI_Bucket     570190
dtype: int64

In [77]:
station_hour.head(20)

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,AP001,2017-11-24 17:00:00,60.50,98.00,2.35,30.80,18.25,8.50,0.1,11.85,126.40,0.10,6.10,0.10,NaN,NaN
1,AP001,2017-11-24 18:00:00,65.50,111.25,2.70,24.20,15.07,9.77,0.1,13.17,117.12,0.10,6.25,0.15,NaN,NaN
2,AP001,2017-11-24 19:00:00,80.00,132.00,2.10,25.18,15.15,12.02,0.1,12.08,98.98,0.20,5.98,0.18,NaN,NaN
3,AP001,2017-11-24 20:00:00,81.50,133.25,1.95,16.25,10.23,11.58,0.1,10.47,112.20,0.20,6.72,0.10,NaN,NaN
4,AP001,2017-11-24 21:00:00,75.25,116.00,1.43,17.48,10.43,12.03,0.1,9.12,106.35,0.20,5.75,0.08,NaN,NaN
5,AP001,2017-11-24 22:00:00,69.25,108.25,0.70,18.47,10.38,13.80,0.1,9.25,91.10,0.20,5.02,0.00,NaN,NaN
6,AP001,2017-11-24 23:00:00,67.50,111.50,1.05,12.15,7.30,17.65,0.1,9.40,112.70,0.20,5.60,0.10,NaN,NaN
7,AP001,2017-11-25 00:00:00,68.00,111.00,1.25,14.12,8.50,20.28,0.1,8.90,116.12,0.20,5.55,0.05,NaN,NaN
8,AP001,2017-11-25 01:00:00,73.00,102.00,0.30,14.30,7.90,11.50,0.3,11.80,121.50,0.20,6.60,0.00,NaN,NaN
9,AP001,2017-11-25 02:00:00,81.00,123.00,0.80,24.85,13.88,10.28,0.1,11.62,83.80,0.23,6.77,0.10,NaN,NaN
10,AP001,2017-11-25 03:00:00,82.50,122.75,1.25,21.82,12.65,10.18,0.1,12.70,87.25,0.20,5.98,0.08,NaN,NaN
11,AP001,2017-11-25 04:00:00,77.50,112.50,0.50,23.50,12.90,8.90,0.1,11.58,76.45,0.20,6.02,0.00,NaN,NaN
12,AP001,2017-11-25 05:00:00,77.00,112.50,1.30,23.58,13.60,8.75,0.1,11.10,101.93,0.20,7.68,0.10,NaN,NaN
13,AP001,2017-11-25 06:00:00,80.75,122.00,1.08,19.20,11.08,9.30,0.1,12.58,107.77,0.20,8.32,0.10,NaN,NaN
14,AP001,2017-11-25 07:00:00,83.00,137.00,2.12,26.03,15.62,7.73,0.1,12.75,93.57,0.28,11.88,0.10,NaN,NaN
15,AP001,2017-11-25 08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,AP001,2017-11-25 09:00:00,104.00,148.50,1.93,23.00,13.75,9.80,0.1,15.30,117.62,0.30,10.40,0.23,155.0,Moderate
17,AP001,2017-11-25 10:00:00,94.50,142.00,1.33,16.25,9.75,9.65,0.1,17.00,136.23,0.28,7.10,0.15,159.0,Moderate
18,AP001,2017-11-25 11:00:00,82.75,126.50,1.47,14.83,9.07,9.70,0.1,15.40,149.92,0.20,4.55,0.08,173.0,Moderate
19,AP001,2017-11-25 12:00:00,79.00,124.00,5.30,21.15,15.53,9.40,0.1,NaN,156.80,0.20,4.00,0.00,184.0,Moderate

In [78]:
import pandas as pd
import numpy as np

print("--- PROCESSING STATION_HOUR (This may take a minute) ---")

# 1. SETUP (Merge City Names)
# We assume station_hour is already loaded. If not, uncomment the next line:
# station_hour = pd.read_csv('station_hour.csv')
station_hour['Datetime'] = pd.to_datetime(station_hour['Datetime'])

if 'City' not in station_hour.columns:
    # Ensure 'stations' dataframe exists (from previous steps)
    station_hour = station_hour.merge(stations[['StationId', 'City']], on='StationId', how='left')

# 2. FILL MISSING POLLUTANTS (The Smart Strategy)
pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3']

print("1. Filling missing pollutant data...")

# A. Interpolate within the same station (Good for short gaps of a few hours)
# We limit direction to avoid drawing lines across massive month-long gaps
for col in pollutants:
    station_hour[col] = station_hour.groupby('StationId')[col].transform(
        lambda x: x.interpolate(method='linear', limit_direction='both')
    )

# B. Fill remaining gaps using the CITY Median for that specific hour
# (If Station A is dead at 10 AM, use the average of Station B & C at 10 AM)
print("   ...Applying City-wide averages (Heavy Step)...")
for col in pollutants:
    station_hour[col] = station_hour[col].fillna(
        station_hour.groupby(['City', 'Datetime'])[col].transform('median')
    )

# C. Fallback: Global Median for that hour (if the whole city is offline)
for col in pollutants:
    station_hour[col] = station_hour[col].fillna(
        station_hour.groupby('Datetime')[col].transform('median')
    )

# D. Final Safety Net (Forward/Back fill)
station_hour[pollutants] = station_hour[pollutants].ffill().bfill()

# 3. RE-DEFINE FORMULAS (Safety measure)
def get_PM25_subindex(x):
    if x <= 30: return x * 50 / 30
    elif x <= 60: return 50 + (x - 30) * 50 / 30
    elif x <= 90: return 100 + (x - 60) * 100 / 30
    elif x <= 120: return 200 + (x - 90) * 100 / 30
    elif x <= 250: return 300 + (x - 120) * 100 / 130
    elif x > 250: return 400 + (x - 250) * 100 / 130
    else: return 0

def get_PM10_subindex(x):
    if x <= 50: return x
    elif x <= 100: return x
    elif x <= 250: return 100 + (x - 100) * 100 / 150
    elif x <= 350: return 200 + (x - 250) * 100 / 100
    elif x <= 430: return 300 + (x - 350) * 100 / 80
    elif x > 430: return 400 + (x - 430) * 100 / 80
    else: return 0

def get_SO2_subindex(x):
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 380: return 100 + (x - 80) * 100 / 300
    elif x <= 800: return 200 + (x - 380) * 100 / 420
    elif x <= 1600: return 300 + (x - 800) * 100 / 800
    elif x > 1600: return 400 + (x - 1600) * 100 / 800
    else: return 0

def get_NOx_subindex(x):
    if x <= 40: return x * 50 / 40
    elif x <= 80: return 50 + (x - 40) * 50 / 40
    elif x <= 180: return 100 + (x - 80) * 100 / 100
    elif x <= 280: return 200 + (x - 180) * 100 / 100
    elif x <= 400: return 300 + (x - 280) * 100 / 120
    elif x > 400: return 400 + (x - 400) * 100 / 120
    else: return 0

def get_NH3_subindex(x):
    if x <= 200: return x * 50 / 200
    elif x <= 400: return 50 + (x - 200) * 50 / 200
    elif x <= 800: return 100 + (x - 400) * 100 / 400
    elif x <= 1200: return 200 + (x - 800) * 100 / 400
    elif x <= 1800: return 300 + (x - 1200) * 100 / 600
    elif x > 1800: return 400 + (x - 1800) * 100 / 600
    else: return 0

def get_CO_subindex(x):
    if x <= 1: return x * 50 / 1
    elif x <= 2: return 50 + (x - 1) * 50 / 1
    elif x <= 10: return 100 + (x - 2) * 100 / 8
    elif x <= 17: return 200 + (x - 10) * 100 / 7
    elif x <= 34: return 300 + (x - 17) * 100 / 17
    elif x > 34: return 400 + (x - 34) * 100 / 17
    else: return 0

def get_O3_subindex(x):
    if x <= 50: return x * 50 / 50
    elif x <= 100: return 50 + (x - 50) * 50 / 50
    elif x <= 168: return 100 + (x - 100) * 100 / 68
    elif x <= 208: return 200 + (x - 168) * 100 / 40
    elif x <= 748: return 300 + (x - 208) * 100 / 539
    elif x > 748: return 400 + (x - 748) * 100 / 539
    else: return 0

def get_aqi_bucket(x):
    if pd.isnull(x): return 'Unknown'
    if x <= 50: return 'Good'
    elif x <= 100: return 'Satisfactory'
    elif x <= 200: return 'Moderate'
    elif x <= 300: return 'Poor'
    elif x <= 400: return 'Very Poor'
    else: return 'Severe'

# 4. CALCULATE AQI
print("2. Calculating AQI (This is the slow part)...")

station_hour['PM2.5_SubIndex'] = station_hour['PM2.5'].apply(lambda x: get_PM25_subindex(x))
station_hour['PM10_SubIndex'] = station_hour['PM10'].apply(lambda x: get_PM10_subindex(x))
station_hour['SO2_SubIndex'] = station_hour['SO2'].apply(lambda x: get_SO2_subindex(x))
station_hour['NOx_SubIndex'] = station_hour['NOx'].apply(lambda x: get_NOx_subindex(x))
station_hour['NH3_SubIndex'] = station_hour['NH3'].apply(lambda x: get_NH3_subindex(x))
station_hour['CO_SubIndex'] = station_hour['CO'].apply(lambda x: get_CO_subindex(x))
station_hour['O3_SubIndex'] = station_hour['O3'].apply(lambda x: get_O3_subindex(x))

station_hour['Calculated_AQI'] = station_hour[[
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex'
]].max(axis=1)

# Overwrite AQI
station_hour['AQI'] = station_hour['Calculated_AQI']
station_hour['AQI_Bucket'] = station_hour['AQI'].apply(get_aqi_bucket)

# 5. CLEANUP
cols_to_drop = [
    'PM2.5_SubIndex', 'PM10_SubIndex', 'SO2_SubIndex', 
    'NOx_SubIndex', 'NH3_SubIndex', 'CO_SubIndex', 'O3_SubIndex', 
    'Calculated_AQI'
]
station_hour.drop(columns=cols_to_drop, inplace=True, errors='ignore')

print("--- STATION_HOUR COMPLETE ---")
print("Remaining Missing AQI:", station_hour['AQI'].isnull().sum())
print(station_hour[['StationId', 'Datetime', 'AQI', 'AQI_Bucket']].tail())

--- PROCESSING STATION_HOUR (This may take a minute) ---
1. Filling missing pollutant data...
   ...Applying City-wide averages (Heavy Step)...
2. Calculating AQI (This is the slow part)...
--- STATION_HOUR COMPLETE ---
Remaining Missing AQI: 0
        StationId            Datetime      AQI    AQI_Bucket
2589078     WB013 2020-06-30 20:00:00  52.9750  Satisfactory
2589079     WB013 2020-06-30 21:00:00  42.3000          Good
2589080     WB013 2020-06-30 22:00:00  40.9500          Good
2589081     WB013 2020-06-30 23:00:00  38.7500          Good
2589082     WB013 2020-07-01 00:00:00  37.8125          Good

In [79]:
station_hour.head(20)

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
0,AP001,2017-11-24 17:00:00,60.50,98.00,2.350,30.800,18.250,8.500,0.1,11.850000,126.400,0.10,6.10,0.10,138.823529,Moderate,Amaravati
1,AP001,2017-11-24 18:00:00,65.50,111.25,2.700,24.200,15.070,9.770,0.1,13.170000,117.120,0.10,6.25,0.15,125.176471,Moderate,Amaravati
2,AP001,2017-11-24 19:00:00,80.00,132.00,2.100,25.180,15.150,12.020,0.1,12.080000,98.980,0.20,5.98,0.18,166.666667,Moderate,Amaravati
3,AP001,2017-11-24 20:00:00,81.50,133.25,1.950,16.250,10.230,11.580,0.1,10.470000,112.200,0.20,6.72,0.10,171.666667,Moderate,Amaravati
4,AP001,2017-11-24 21:00:00,75.25,116.00,1.430,17.480,10.430,12.030,0.1,9.120000,106.350,0.20,5.75,0.08,150.833333,Moderate,Amaravati
5,AP001,2017-11-24 22:00:00,69.25,108.25,0.700,18.470,10.380,13.800,0.1,9.250000,91.100,0.20,5.02,0.00,130.833333,Moderate,Amaravati
6,AP001,2017-11-24 23:00:00,67.50,111.50,1.050,12.150,7.300,17.650,0.1,9.400000,112.700,0.20,5.60,0.10,125.000000,Moderate,Amaravati
7,AP001,2017-11-25 00:00:00,68.00,111.00,1.250,14.120,8.500,20.280,0.1,8.900000,116.120,0.20,5.55,0.05,126.666667,Moderate,Amaravati
8,AP001,2017-11-25 01:00:00,73.00,102.00,0.300,14.300,7.900,11.500,0.3,11.800000,121.500,0.20,6.60,0.00,143.333333,Moderate,Amaravati
9,AP001,2017-11-25 02:00:00,81.00,123.00,0.800,24.850,13.880,10.280,0.1,11.620000,83.800,0.23,6.77,0.10,170.000000,Moderate,Amaravati
10,AP001,2017-11-25 03:00:00,82.50,122.75,1.250,21.820,12.650,10.180,0.1,12.700000,87.250,0.20,5.98,0.08,175.000000,Moderate,Amaravati
11,AP001,2017-11-25 04:00:00,77.50,112.50,0.500,23.500,12.900,8.900,0.1,11.580000,76.450,0.20,6.02,0.00,158.333333,Moderate,Amaravati
12,AP001,2017-11-25 05:00:00,77.00,112.50,1.300,23.580,13.600,8.750,0.1,11.100000,101.930,0.20,7.68,0.10,156.666667,Moderate,Amaravati
13,AP001,2017-11-25 06:00:00,80.75,122.00,1.080,19.200,11.080,9.300,0.1,12.580000,107.770,0.20,8.32,0.10,169.166667,Moderate,Amaravati
14,AP001,2017-11-25 07:00:00,83.00,137.00,2.120,26.030,15.620,7.730,0.1,12.750000,93.570,0.28,11.88,0.10,176.666667,Moderate,Amaravati
15,AP001,2017-11-25 08:00:00,93.50,142.75,2.025,24.515,14.685,8.765,0.1,14.025000,105.595,NaN,NaN,NaN,211.666667,Poor,Amaravati
16,AP001,2017-11-25 09:00:00,104.00,148.50,1.930,23.000,13.750,9.800,0.1,15.300000,117.620,0.30,10.40,0.23,246.666667,Poor,Amaravati
17,AP001,2017-11-25 10:00:00,94.50,142.00,1.330,16.250,9.750,9.650,0.1,17.000000,136.230,0.28,7.10,0.15,215.000000,Poor,Amaravati
18,AP001,2017-11-25 11:00:00,82.75,126.50,1.470,14.830,9.070,9.700,0.1,15.400000,149.920,0.20,4.55,0.08,175.833333,Moderate,Amaravati
19,AP001,2017-11-25 12:00:00,79.00,124.00,5.300,21.150,15.530,9.400,0.1,17.533333,156.800,0.20,4.00,0.00,183.529412,Moderate,Amaravati

In [80]:
station_hour.isnull().sum()

StationId           0
Datetime            0
PM2.5               0
PM10                0
NO                  0
NO2                 0
NOx                 0
NH3                 0
CO                  0
SO2                 0
O3                  0
Benzene        861579
Toluene       1042366
Xylene        2075104
AQI                 0
AQI_Bucket          0
City                0
dtype: int64

In [81]:
station_hour.tail(20)

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
2589063,WB013,2020-06-30 05:00:00,12.53,35.43,9.661364,77.235,86.85,25.503636,0.72,1.65,8.01,1.08,6.74,NaN,106.8500,Moderate,Kolkata
2589064,WB013,2020-06-30 06:00:00,10.10,35.20,9.205455,68.740,77.90,26.174545,0.76,1.77,7.41,1.67,7.21,NaN,97.3750,Satisfactory,Kolkata
2589065,WB013,2020-06-30 07:00:00,12.07,37.92,8.749545,60.245,68.95,26.845455,0.77,2.80,8.68,1.58,7.26,NaN,86.1875,Satisfactory,Kolkata
2589066,WB013,2020-06-30 08:00:00,16.65,36.38,8.293636,51.750,60.00,27.516364,0.73,3.75,20.20,1.76,7.79,NaN,75.0000,Satisfactory,Kolkata
2589067,WB013,2020-06-30 09:00:00,19.47,32.03,7.837727,43.255,51.05,28.187273,0.62,3.67,45.15,1.15,8.19,NaN,63.8125,Satisfactory,Kolkata
2589068,WB013,2020-06-30 10:00:00,15.65,32.17,7.381818,34.760,42.10,28.858182,0.67,4.18,54.26,0.87,8.30,NaN,54.2600,Satisfactory,Kolkata
2589069,WB013,2020-06-30 11:00:00,13.95,29.50,6.925909,26.265,33.15,29.529091,0.68,4.09,59.05,0.98,8.13,NaN,59.0500,Satisfactory,Kolkata
2589070,WB013,2020-06-30 12:00:00,14.47,37.48,6.470000,17.770,24.20,30.200000,0.65,3.04,57.15,0.96,7.71,NaN,57.1500,Satisfactory,Kolkata
2589071,WB013,2020-06-30 13:00:00,13.15,39.70,5.930000,15.260,21.23,31.770000,0.61,2.86,59.10,1.15,7.20,NaN,59.1000,Satisfactory,Kolkata
2589072,WB013,2020-06-30 14:00:00,18.65,36.40,7.350000,28.770,36.15,32.830000,0.71,2.46,42.47,1.16,7.81,NaN,45.1875,Good,Kolkata
2589073,WB013,2020-06-30 15:00:00,22.82,36.75,9.850000,49.860,59.73,26.280000,0.85,3.08,32.38,1.40,6.82,NaN,74.6625,Satisfactory,Kolkata
2589074,WB013,2020-06-30 16:00:00,23.00,42.30,6.950000,32.790,39.72,23.680000,0.70,6.25,57.22,3.18,11.62,NaN,57.2200,Satisfactory,Kolkata
2589075,WB013,2020-06-30 17:00:00,17.72,47.25,7.420000,26.540,33.95,25.610000,0.78,8.81,58.96,1.60,8.50,NaN,58.9600,Satisfactory,Kolkata
2589076,WB013,2020-06-30 18:00:00,14.45,42.42,9.320000,38.910,48.25,26.210000,0.81,34.88,27.57,2.13,9.35,NaN,60.3125,Satisfactory,Kolkata
2589077,WB013,2020-06-30 19:00:00,12.35,44.88,8.280000,36.440,44.70,32.300000,0.78,23.99,16.45,2.13,9.47,NaN,55.8750,Satisfactory,Kolkata
2589078,WB013,2020-06-30 20:00:00,15.55,47.80,7.270000,35.080,42.38,31.250000,0.80,9.40,17.24,2.56,11.57,NaN,52.9750,Satisfactory,Kolkata
2589079,WB013,2020-06-30 21:00:00,15.23,42.30,6.100000,26.780,32.85,30.660000,0.56,4.91,17.46,3.49,12.29,NaN,42.3000,Good,Kolkata
2589080,WB013,2020-06-30 22:00:00,11.40,40.95,6.580000,19.530,26.12,30.730000,0.61,3.81,17.24,1.83,8.88,NaN,40.9500,Good,Kolkata
2589081,WB013,2020-06-30 23:00:00,9.25,34.33,9.170000,21.850,31.00,29.610000,0.65,3.44,12.74,1.40,8.43,NaN,38.7500,Good,Kolkata
2589082,WB013,2020-07-01 00:00:00,10.50,36.50,7.780000,22.500,30.25,27.230000,0.58,2.80,13.10,1.31,7.39,NaN,37.8125,Good,Kolkata

FINAL SUMMARY

In [82]:
city_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  datetime64[ns]
 2   PM2.5       29531 non-null  float64
 3   PM10        27522 non-null  float64
 4   NO          29531 non-null  float64
 5   NO2         29531 non-null  float64
 6   NOx         28362 non-null  float64
 7   NH3         27522 non-null  float64
 8   CO          29531 non-null  float64
 9   SO2         29531 non-null  float64
 10  O3          29369 non-null  float64
 11  Benzene     26799 non-null  float64
 12  Toluene     25521 non-null  float64
 13  Xylene      16484 non-null  float64
 14  AQI         29531 non-null  float64
 15  AQI_Bucket  29531 non-null  object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 3.6+ MB

In [83]:
city_day.head(20)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,73.24,141.54,0.920,18.22,17.15,NaN,0.920,27.64,133.36,0.00,0.02,0.00,149.568235,Moderate
1,Ahmedabad,2015-01-02,73.24,141.54,0.970,15.69,16.46,NaN,0.970,24.55,34.06,3.68,5.50,3.77,144.692000,Moderate
2,Ahmedabad,2015-01-03,73.24,141.54,17.400,19.30,29.70,NaN,17.400,29.07,30.70,6.80,16.40,2.25,303.329412,Very Poor
3,Ahmedabad,2015-01-04,73.24,141.54,1.700,18.48,17.97,NaN,1.700,18.59,36.08,4.43,10.14,1.00,144.692000,Moderate
4,Ahmedabad,2015-01-05,73.24,141.54,22.100,21.42,37.76,NaN,22.100,39.33,39.31,7.01,18.89,2.78,330.700000,Very Poor
5,Ahmedabad,2015-01-06,73.24,141.54,45.410,38.48,81.50,NaN,45.410,45.76,46.51,5.42,10.83,1.93,401.113356,Severe
6,Ahmedabad,2015-01-07,73.24,141.54,112.160,40.62,130.77,NaN,112.160,32.28,33.47,0.00,0.00,0.00,401.776502,Severe
7,Ahmedabad,2015-01-08,73.24,141.54,80.870,36.74,96.75,NaN,80.870,38.54,31.89,0.00,0.00,0.00,401.465643,Severe
8,Ahmedabad,2015-01-09,73.24,141.54,29.160,31.00,48.00,NaN,29.160,58.68,25.75,0.00,0.00,0.00,371.814118,Very Poor
9,Ahmedabad,2015-01-10,73.24,141.54,80.615,7.04,0.00,NaN,80.615,8.29,4.55,0.00,0.00,0.00,401.463109,Severe
10,Ahmedabad,2015-01-11,73.24,141.54,132.070,55.80,24.53,NaN,132.070,25.03,6.79,0.00,0.00,0.00,401.974303,Severe
11,Ahmedabad,2015-01-12,73.24,141.54,52.040,40.67,90.24,NaN,52.040,51.84,45.89,2.41,0.03,7.88,401.179223,Severe
12,Ahmedabad,2015-01-13,73.24,141.54,48.820,44.20,87.09,NaN,48.820,68.21,35.16,9.45,13.35,12.50,401.147233,Severe
13,Ahmedabad,2015-01-14,73.24,141.54,19.200,27.86,33.05,NaN,19.200,52.65,20.96,2.16,2.26,5.19,313.811765,Very Poor
14,Ahmedabad,2015-01-15,73.24,141.54,0.600,16.96,16.60,NaN,0.600,28.89,47.63,0.14,0.04,1.35,144.692000,Moderate
15,Ahmedabad,2015-01-16,73.24,141.54,1.630,21.72,22.86,NaN,1.630,38.27,46.03,0.35,0.05,2.01,144.692000,Moderate
16,Ahmedabad,2015-01-17,73.24,141.54,11.440,24.73,34.75,NaN,11.440,49.50,52.24,0.68,0.00,3.27,221.365714,Poor
17,Ahmedabad,2015-01-18,73.24,141.54,6.100,25.77,29.57,NaN,6.100,48.43,53.49,0.74,0.21,2.75,151.737500,Moderate
18,Ahmedabad,2015-01-19,73.24,141.54,2.510,26.88,27.45,NaN,2.510,50.03,49.48,0.26,0.02,2.80,144.692000,Moderate
19,Ahmedabad,2015-01-20,73.24,141.54,7.920,26.80,32.40,NaN,7.920,58.87,56.37,0.24,0.01,3.97,174.260000,Moderate

In [85]:
city_day.isnull().sum()    #this shit, aqi was calculated using interpoliation

City              0
Date              0
PM2.5             0
PM10           2009
NO                0
NO2               0
NOx            1169
NH3            2009
CO                0
SO2               0
O3              162
Benzene        2732
Toluene        4010
Xylene        13047
AQI               0
AQI_Bucket        0
dtype: int64

In [86]:
city_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707875 entries, 0 to 707874
Data columns (total 18 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   City        707875 non-null  object
 1   Datetime    707875 non-null  datetime64[ns]
 2   PM2.5       707875 non-null  float64
 3   PM10        707875 non-null  float64
 4   NO          591243 non-null  float64
 5   NO2         707875 non-null  float64
 6   NOx         584651 non-null  float64
 7   NH3         707875 non-null  float64
 8   CO          707875 non-null  float64
 9   SO2         707875 non-null  float64
 10  O3          707875 non-null  float64
 11  Benzene     544229 non-null  float64
 12  Toluene     487268 non-null  float64
 13  Xylene      252046 non-null  float64
 14  AQI         707875 non-null  float64
 15  AQI_Bucket  707875 non-null  object
 16  Date        707875 non-null  object
 17  Time        707875 non-null  object
dtypes: datetime64[ns](1), float64(13), object(4)
memory usage: 97.2+ MB

In [87]:
city_hour.head(20)

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Date,Time
0,Ahmedabad,2015-01-01 01:00:00,36.6,120.06,1.00,40.01,36.37,19.88,1.00,122.07,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,01:00:00
1,Ahmedabad,2015-01-01 02:00:00,36.6,120.06,0.02,27.75,19.73,19.88,0.02,85.90,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,02:00:00
2,Ahmedabad,2015-01-01 03:00:00,36.6,120.06,0.08,19.32,11.08,19.88,0.08,52.83,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,03:00:00
3,Ahmedabad,2015-01-01 04:00:00,36.6,120.06,0.30,16.45,9.20,19.88,0.30,39.53,153.580000,0.0,0.00,0.0,178.794118,Moderate,2015-01-01,04:00:00
4,Ahmedabad,2015-01-01 05:00:00,36.6,120.06,0.12,14.90,7.85,19.88,0.12,32.63,108.915000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,05:00:00
5,Ahmedabad,2015-01-01 06:00:00,36.6,120.06,0.33,15.95,10.82,19.88,0.33,29.87,64.250000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,06:00:00
6,Ahmedabad,2015-01-01 07:00:00,36.6,120.06,0.45,15.94,12.47,19.88,0.45,27.41,191.960000,0.0,0.00,0.0,259.900000,Poor,2015-01-01,07:00:00
7,Ahmedabad,2015-01-01 08:00:00,36.6,120.06,1.03,16.66,16.48,19.88,1.03,20.92,177.210000,0.0,0.00,0.0,223.025000,Poor,2015-01-01,08:00:00
8,Ahmedabad,2015-01-01 09:00:00,36.6,120.06,1.47,16.25,18.02,19.88,1.47,16.45,122.080000,0.0,0.00,0.0,132.470588,Moderate,2015-01-01,09:00:00
9,Ahmedabad,2015-01-01 10:00:00,36.6,120.06,2.05,13.78,16.08,19.88,2.05,15.14,110.625000,0.0,0.00,0.0,115.625000,Moderate,2015-01-01,10:00:00
10,Ahmedabad,2015-01-01 11:00:00,36.6,120.06,2.27,13.87,16.73,19.88,2.27,14.12,99.170000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,11:00:00
11,Ahmedabad,2015-01-01 12:00:00,36.6,120.06,1.73,12.87,14.63,19.88,1.73,13.26,91.670000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,12:00:00
12,Ahmedabad,2015-01-01 13:00:00,36.6,120.06,1.72,14.15,15.55,19.88,1.72,17.20,95.920000,0.0,0.00,0.0,113.373333,Moderate,2015-01-01,13:00:00
13,Ahmedabad,2015-01-01 14:00:00,36.6,120.06,1.85,15.74,17.62,19.88,1.85,18.78,118.845000,0.0,0.00,0.0,127.713235,Moderate,2015-01-01,14:00:00
14,Ahmedabad,2015-01-01 15:00:00,36.6,120.06,0.95,15.94,16.18,19.88,0.95,19.16,141.770000,0.0,0.00,0.0,161.426471,Moderate,2015-01-01,15:00:00
15,Ahmedabad,2015-01-01 16:00:00,36.6,120.06,0.87,17.28,18.32,19.88,0.87,17.83,164.695000,0.0,0.00,0.0,195.139706,Moderate,2015-01-01,16:00:00
16,Ahmedabad,2015-01-01 17:00:00,36.6,120.06,0.80,19.04,20.00,19.88,0.80,16.14,187.620000,0.0,0.00,0.0,249.050000,Poor,2015-01-01,17:00:00
17,Ahmedabad,2015-01-01 18:00:00,36.6,120.06,0.47,21.24,22.70,19.88,0.47,11.93,187.553333,0.0,0.00,0.0,248.883333,Poor,2015-01-01,18:00:00
18,Ahmedabad,2015-01-01 19:00:00,36.6,120.06,0.53,25.63,27.42,19.88,0.53,14.99,187.486667,0.0,0.33,0.0,248.716667,Poor,2015-01-01,19:00:00
19,Ahmedabad,2015-01-01 20:00:00,36.6,120.06,0.47,16.22,16.00,19.88,0.47,13.66,187.420000,0.0,0.23,0.0,248.550000,Poor,2015-01-01,20:00:00

In [88]:
city_hour.isnull().sum()

City               0
Datetime           0
PM2.5              0
PM10               0
NO            116632
NO2                0
NOx           123224
NH3                0
CO                 0
SO2                0
O3                 0
Benzene       163646
Toluene       220607
Xylene        455829
AQI                0
AQI_Bucket         0
Date               0
Time               0
dtype: int64

In [89]:
station_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108035 entries, 0 to 108034
Data columns (total 17 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   StationId   108035 non-null  object
 1   Date        108035 non-null  datetime64[ns]
 2   PM2.5       108035 non-null  float64
 3   PM10        108035 non-null  float64
 4   NO          108035 non-null  float64
 5   NO2         108035 non-null  float64
 6   NOx         108035 non-null  float64
 7   NH3         108035 non-null  float64
 8   CO          108035 non-null  float64
 9   SO2         108035 non-null  float64
 10  O3          108035 non-null  float64
 11  Benzene     76580 non-null   float64
 12  Toluene     69333 non-null   float64
 13  Xylene      22898 non-null   float64
 14  AQI         108035 non-null  float64
 15  AQI_Bucket  108035 non-null  object
 16  City        108035 non-null  object
dtypes: datetime64[ns](1), float64(13), object(3)
memory usage: 14.0+ MB

In [90]:
station_day.head(20)

,StationId,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
0,AP001,2017-11-24,71.36,115.75,1.75,20.65,12.40,12.19,0.10,10.76,109.26,0.17,5.92,0.10,137.866667,Moderate,Amaravati
1,AP001,2017-11-25,81.40,124.50,1.44,20.50,12.08,10.72,0.12,15.24,127.09,0.20,6.50,0.06,171.333333,Moderate,Amaravati
2,AP001,2017-11-26,78.32,129.06,1.26,26.00,14.85,10.28,0.14,26.96,117.44,0.22,7.95,0.08,161.066667,Moderate,Amaravati
3,AP001,2017-11-27,88.76,135.32,6.60,30.85,21.77,12.91,0.11,33.59,111.81,0.29,7.63,0.12,195.866667,Moderate,Amaravati
4,AP001,2017-11-28,64.18,104.09,2.56,28.07,17.01,11.42,0.09,19.00,138.18,0.17,5.02,0.07,156.147059,Moderate,Amaravati
5,AP001,2017-11-29,72.47,114.84,5.23,23.20,16.59,12.25,0.16,10.55,109.74,0.21,4.71,0.08,141.566667,Moderate,Amaravati
6,AP001,2017-11-30,69.80,114.86,4.69,20.17,14.54,10.95,0.12,14.07,118.09,0.16,3.52,0.06,132.666667,Moderate,Amaravati
7,AP001,2017-12-01,73.96,113.56,4.58,19.29,13.97,10.95,0.10,13.90,123.80,0.17,2.85,0.04,146.533333,Moderate,Amaravati
8,AP001,2017-12-02,89.90,140.20,7.71,26.19,19.87,13.12,0.10,19.37,128.73,0.25,2.79,0.07,199.666667,Moderate,Amaravati
9,AP001,2017-12-03,87.14,130.52,0.97,21.31,12.12,14.36,0.15,11.41,114.80,0.23,3.82,0.04,190.466667,Moderate,Amaravati
10,AP001,2017-12-04,84.64,125.00,4.02,26.98,17.58,14.41,0.18,9.84,112.41,0.31,3.53,0.09,182.133333,Moderate,Amaravati
11,AP001,2017-12-05,88.36,121.77,3.70,20.23,13.75,13.72,0.12,14.02,117.93,0.24,2.92,0.03,194.533333,Moderate,Amaravati
12,AP001,2017-12-06,96.83,139.36,1.60,25.65,14.99,15.12,0.11,16.54,117.21,0.29,4.45,0.07,222.766667,Poor,Amaravati
13,AP001,2017-12-07,117.46,181.64,4.26,41.10,25.32,17.34,0.13,28.79,94.63,0.36,6.21,0.17,291.533333,Poor,Amaravati
14,AP001,2017-12-08,122.88,208.86,5.56,54.87,33.71,17.96,0.27,22.97,68.60,0.36,6.28,0.21,302.215385,Very Poor,Amaravati
15,AP001,2017-12-09,74.28,141.22,6.10,44.97,28.88,15.73,0.09,21.90,60.62,0.26,4.79,0.16,147.600000,Moderate,Amaravati
16,AP001,2017-12-10,50.32,102.77,1.73,33.85,19.41,12.56,0.10,13.65,68.15,0.20,4.29,0.10,101.846667,Moderate,Amaravati
17,AP001,2017-12-11,58.47,115.27,4.93,41.64,26.15,15.20,0.16,18.37,73.75,0.23,5.51,0.16,110.180000,Moderate,Amaravati
18,AP001,2017-12-12,89.35,131.48,7.97,42.10,28.88,21.24,0.24,7.42,44.67,0.28,7.01,0.19,197.833333,Moderate,Amaravati
19,AP001,2017-12-13,64.42,99.74,7.20,34.78,24.36,17.63,0.15,5.81,50.16,0.24,6.11,0.14,114.733333,Moderate,Amaravati

In [91]:
station_day.isnull().sum()

StationId         0
Date              0
PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
CO                0
SO2               0
O3                0
Benzene       31455
Toluene       38702
Xylene        85137
AQI               0
AQI_Bucket        0
City              0
dtype: int64

In [92]:
station_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2589083 entries, 0 to 2589082
Data columns (total 17 columns):
 #   Column      Dtype
---  ------      -----
 0   StationId   object
 1   Datetime    datetime64[ns]
 2   PM2.5       float64
 3   PM10        float64
 4   NO          float64
 5   NO2         float64
 6   NOx         float64
 7   NH3         float64
 8   CO          float64
 9   SO2         float64
 10  O3          float64
 11  Benzene     float64
 12  Toluene     float64
 13  Xylene      float64
 14  AQI         float64
 15  AQI_Bucket  object
 16  City        object
dtypes: datetime64[ns](1), float64(13), object(3)
memory usage: 335.8+ MB

In [93]:
station_hour.head(20)

,StationId,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,City
0,AP001,2017-11-24 17:00:00,60.50,98.00,2.350,30.800,18.250,8.500,0.1,11.850000,126.400,0.10,6.10,0.10,138.823529,Moderate,Amaravati
1,AP001,2017-11-24 18:00:00,65.50,111.25,2.700,24.200,15.070,9.770,0.1,13.170000,117.120,0.10,6.25,0.15,125.176471,Moderate,Amaravati
2,AP001,2017-11-24 19:00:00,80.00,132.00,2.100,25.180,15.150,12.020,0.1,12.080000,98.980,0.20,5.98,0.18,166.666667,Moderate,Amaravati
3,AP001,2017-11-24 20:00:00,81.50,133.25,1.950,16.250,10.230,11.580,0.1,10.470000,112.200,0.20,6.72,0.10,171.666667,Moderate,Amaravati
4,AP001,2017-11-24 21:00:00,75.25,116.00,1.430,17.480,10.430,12.030,0.1,9.120000,106.350,0.20,5.75,0.08,150.833333,Moderate,Amaravati
5,AP001,2017-11-24 22:00:00,69.25,108.25,0.700,18.470,10.380,13.800,0.1,9.250000,91.100,0.20,5.02,0.00,130.833333,Moderate,Amaravati
6,AP001,2017-11-24 23:00:00,67.50,111.50,1.050,12.150,7.300,17.650,0.1,9.400000,112.700,0.20,5.60,0.10,125.000000,Moderate,Amaravati
7,AP001,2017-11-25 00:00:00,68.00,111.00,1.250,14.120,8.500,20.280,0.1,8.900000,116.120,0.20,5.55,0.05,126.666667,Moderate,Amaravati
8,AP001,2017-11-25 01:00:00,73.00,102.00,0.300,14.300,7.900,11.500,0.3,11.800000,121.500,0.20,6.60,0.00,143.333333,Moderate,Amaravati
9,AP001,2017-11-25 02:00:00,81.00,123.00,0.800,24.850,13.880,10.280,0.1,11.620000,83.800,0.23,6.77,0.10,170.000000,Moderate,Amaravati
10,AP001,2017-11-25 03:00:00,82.50,122.75,1.250,21.820,12.650,10.180,0.1,12.700000,87.250,0.20,5.98,0.08,175.000000,Moderate,Amaravati
11,AP001,2017-11-25 04:00:00,77.50,112.50,0.500,23.500,12.900,8.900,0.1,11.580000,76.450,0.20,6.02,0.00,158.333333,Moderate,Amaravati
12,AP001,2017-11-25 05:00:00,77.00,112.50,1.300,23.580,13.600,8.750,0.1,11.100000,101.930,0.20,7.68,0.10,156.666667,Moderate,Amaravati
13,AP001,2017-11-25 06:00:00,80.75,122.00,1.080,19.200,11.080,9.300,0.1,12.580000,107.770,0.20,8.32,0.10,169.166667,Moderate,Amaravati
14,AP001,2017-11-25 07:00:00,83.00,137.00,2.120,26.030,15.620,7.730,0.1,12.750000,93.570,0.28,11.88,0.10,176.666667,Moderate,Amaravati
15,AP001,2017-11-25 08:00:00,93.50,142.75,2.025,24.515,14.685,8.765,0.1,14.025000,105.595,NaN,NaN,NaN,211.666667,Poor,Amaravati
16,AP001,2017-11-25 09:00:00,104.00,148.50,1.930,23.000,13.750,9.800,0.1,15.300000,117.620,0.30,10.40,0.23,246.666667,Poor,Amaravati
17,AP001,2017-11-25 10:00:00,94.50,142.00,1.330,16.250,9.750,9.650,0.1,17.000000,136.230,0.28,7.10,0.15,215.000000,Poor,Amaravati
18,AP001,2017-11-25 11:00:00,82.75,126.50,1.470,14.830,9.070,9.700,0.1,15.400000,149.920,0.20,4.55,0.08,175.833333,Moderate,Amaravati
19,AP001,2017-11-25 12:00:00,79.00,124.00,5.300,21.150,15.530,9.400,0.1,17.533333,156.800,0.20,4.00,0.00,183.529412,Moderate,Amaravati

In [94]:
station_hour.isnull().sum()

StationId           0
Datetime            0
PM2.5               0
PM10                0
NO                  0
NO2                 0
NOx                 0
NH3                 0
CO                  0
SO2                 0
O3                  0
Benzene        861579
Toluene       1042366
Xylene        2075104
AQI                 0
AQI_Bucket          0
City                0
dtype: int64

In [95]:
stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StationId    230 non-null    object
 1   StationName  230 non-null    object
 2   City         230 non-null    object
 3   State        230 non-null    object
 4   Status       133 non-null    object
dtypes: object(5)
memory usage: 9.1+ KB

In [96]:
stations.head(20)

,StationId,StationName,City,State,Status
0,AP001,"Secretariat, Amaravati - APPCB",Amaravati,Andhra Pradesh,Active
1,AP002,"Anand Kala Kshetram, Rajamahendravaram - APPCB",Rajamahendravaram,Andhra Pradesh,NaN
2,AP003,"Tirumala, Tirupati - APPCB",Tirupati,Andhra Pradesh,NaN
3,AP004,"PWD Grounds, Vijayawada - APPCB",Vijayawada,Andhra Pradesh,NaN
4,AP005,"GVM Corporation, Visakhapatnam - APPCB",Visakhapatnam,Andhra Pradesh,Active
5,AS001,"Railway Colony, Guwahati - APCB",Guwahati,Assam,Active
6,BR001,"Collectorate, Gaya - BSPCB",Gaya,Bihar,NaN
7,BR002,"SFTI Kusdihra, Gaya - BSPCB",Gaya,Bihar,NaN
8,BR003,"Industrial Area, Hajipur - BSPCB",Hajipur,Bihar,NaN
9,BR004,"Muzaffarpur Collectorate, Muzaffarpur - BSPCB",Muzaffarpur,Bihar,NaN
10,BR005,"DRM Office Danapur, Patna - BSPCB",Patna,Bihar,Active
11,BR006,"Govt. High School Shikarpur, Patna - BSPCB",Patna,Bihar,Active
12,BR007,"IGSC Planetarium Complex, Patna - BSPCB",Patna,Bihar,Active
13,BR008,"Muradpur, Patna - BSPCB",Patna,Bihar,Active
14,BR009,"Rajbansi Nagar, Patna - BSPCB",Patna,Bihar,Active
15,BR010,"Samanpura, Patna - BSPCB",Patna,Bihar,Active
16,CH001,"Sector-25, Chandigarh - CPCC",Chandigarh,Chandigarh,Active
17,DL001,"Alipur, Delhi - DPCC",Delhi,Delhi,Active
18,DL002,"Anand Vihar, Delhi - DPCC",Delhi,Delhi,Active
19,DL003,"Ashok Vihar, Delhi - DPCC",Delhi,Delhi,Active

In [98]:
stations.isnull().sum()

StationId       0
StationName     0
City            0
State           0
Status         97
dtype: int64

In [99]:
stations['Status'] = stations['Status'].fillna('Unknown')

In [100]:
stations.isnull().sum()

StationId      0
StationName    0
City           0
State          0
Status         0
dtype: int64

In [101]:
stations.head(20)

,StationId,StationName,City,State,Status
0,AP001,"Secretariat, Amaravati - APPCB",Amaravati,Andhra Pradesh,Active
1,AP002,"Anand Kala Kshetram, Rajamahendravaram - APPCB",Rajamahendravaram,Andhra Pradesh,Unknown
2,AP003,"Tirumala, Tirupati - APPCB",Tirupati,Andhra Pradesh,Unknown
3,AP004,"PWD Grounds, Vijayawada - APPCB",Vijayawada,Andhra Pradesh,Unknown
4,AP005,"GVM Corporation, Visakhapatnam - APPCB",Visakhapatnam,Andhra Pradesh,Active
5,AS001,"Railway Colony, Guwahati - APCB",Guwahati,Assam,Active
6,BR001,"Collectorate, Gaya - BSPCB",Gaya,Bihar,Unknown
7,BR002,"SFTI Kusdihra, Gaya - BSPCB",Gaya,Bihar,Unknown
8,BR003,"Industrial Area, Hajipur - BSPCB",Hajipur,Bihar,Unknown
9,BR004,"Muzaffarpur Collectorate, Muzaffarpur - BSPCB",Muzaffarpur,Bihar,Unknown
10,BR005,"DRM Office Danapur, Patna - BSPCB",Patna,Bihar,Active
11,BR006,"Govt. High School Shikarpur, Patna - BSPCB",Patna,Bihar,Active
12,BR007,"IGSC Planetarium Complex, Patna - BSPCB",Patna,Bihar,Active
13,BR008,"Muradpur, Patna - BSPCB",Patna,Bihar,Active
14,BR009,"Rajbansi Nagar, Patna - BSPCB",Patna,Bihar,Active
15,BR010,"Samanpura, Patna - BSPCB",Patna,Bihar,Active
16,CH001,"Sector-25, Chandigarh - CPCC",Chandigarh,Chandigarh,Active
17,DL001,"Alipur, Delhi - DPCC",Delhi,Delhi,Active
18,DL002,"Anand Vihar, Delhi - DPCC",Delhi,Delhi,Active
19,DL003,"Ashok Vihar, Delhi - DPCC",Delhi,Delhi,Active

In [102]:
print("Saving cleaned files...")

# 1. Save City Data
city_day.to_csv('city_day_cleaned.csv', index=False)
city_hour.to_csv('city_hour_cleaned.csv', index=False)

# 2. Save Station Data
station_day.to_csv('station_day_cleaned.csv', index=False)
station_hour.to_csv('station_hour_cleaned.csv', index=False)

# Save the stations file
stations.to_csv('stations_cleaned.csv', index=False)


print("SUCCESS! All 5 files have been saved:")
print("1. city_day_cleaned.csv")
print("2. city_hour_cleaned.csv")
print("3. station_day_cleaned.csv")
print("4. station_hour_cleaned.csv")
print("5. stations_cleaned.csv saved successfully.")

Saving cleaned files...
SUCCESS! All 5 files have been saved:
1. city_day_cleaned.csv
2. city_hour_cleaned.csv
3. station_day_cleaned.csv
4. station_hour_cleaned.csv
5. stations_cleaned.csv saved successfully.